/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: onkH1pA6HdPM1JMb3Mte45
// Component: fTShO2Wu4vDW

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/projectcss
import sty from "./PlasmicFloorplans.module.css"; // plasmic-import: fTShO2Wu4vDW/css

import Vector1Icon from "./icons/PlasmicIcon__Vector1"; // plasmic-import: f68eVSSD6GHl/icon
import Icon7Icon from "./icons/PlasmicIcon__Icon7"; // plasmic-import: 6qGWRE-38yD0/icon
import Arrow2Icon from "./icons/PlasmicIcon__Arrow2"; // plasmic-import: SXieq0M2bzak/icon
import ArrowIcon from "./icons/PlasmicIcon__Arrow"; // plasmic-import: LrzIpY4AIRk_/icon

createPlasmicElementProxy;

export type PlasmicFloorplans__VariantMembers = {};
export type PlasmicFloorplans__VariantsArgs = {};
type VariantPropType = keyof PlasmicFloorplans__VariantsArgs;
export const PlasmicFloorplans__VariantProps = new Array<VariantPropType>();

export type PlasmicFloorplans__ArgsType = {};
type ArgPropType = keyof PlasmicFloorplans__ArgsType;
export const PlasmicFloorplans__ArgProps = new Array<ArgPropType>();

export type PlasmicFloorplans__OverridesType = {
  root?: Flex__<"div">;
  floorplans?: Flex__<"div">;
  halfBg3?: Flex__<"div">;
  results2?: Flex__<"div">;
  title2?: Flex__<"div">;
  badge2?: Flex__<"div">;
  content?: Flex__<"div">;
  tabs?: Flex__<"div">;
  tab?: Flex__<"div">;
  title3?: Flex__<"div">;
  options?: Flex__<"div">;
  _7?: Flex__<"div">;
  _8?: Flex__<"div">;
  _9?: Flex__<"div">;
  button?: Flex__<"button">;
  cards2?: Flex__<"div">;
  card2?: Flex__<"div">;
  imageWithFallback2?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  viewMore2?: Flex__<"div">;
  pagination2?: Flex__<"div">;
  number2?: Flex__<"div">;
  _10?: Flex__<"div">;
  _11?: Flex__<"div">;
  _12?: Flex__<"div">;
  _13?: Flex__<"div">;
  freeBox?: Flex__<"div">;
};

export interface DefaultFloorplansProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFloorplans__RenderFunc(props: {
  variants: PlasmicFloorplans__VariantsArgs;
  args: PlasmicFloorplans__ArgsType;
  overrides: PlasmicFloorplans__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"floorplans"}
            data-plasmic-override={overrides.floorplans}
            className={classNames(projectcss.all, sty.floorplans)}
          >
            <div
              data-plasmic-name={"halfBg3"}
              data-plasmic-override={overrides.halfBg3}
              className={classNames(projectcss.all, sty.halfBg3)}
            />

            <div
              data-plasmic-name={"results2"}
              data-plasmic-override={overrides.results2}
              className={classNames(projectcss.all, sty.results2)}
            >
              <div
                data-plasmic-name={"title2"}
                data-plasmic-override={overrides.title2}
                className={classNames(projectcss.all, sty.title2)}
              >
                <div
                  data-plasmic-name={"badge2"}
                  data-plasmic-override={overrides.badge2}
                  className={classNames(projectcss.all, sty.badge2)}
                >
                  <Vector1Icon
                    className={classNames(projectcss.all, sty.svg__w5ECz)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xq7Wu
                    )}
                  >
                    {"Floorplans + 3D Walkthroughs"}
                  </div>
                </div>
                {false ? (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8OfIa
                    )}
                  >
                    {"Nigeria Developments"}
                  </div>
                ) : null}
              </div>
              <div
                data-plasmic-name={"content"}
                data-plasmic-override={overrides.content}
                className={classNames(projectcss.all, sty.content)}
              >
                <div
                  data-plasmic-name={"tabs"}
                  data-plasmic-override={overrides.tabs}
                  className={classNames(projectcss.all, sty.tabs)}
                >
                  <div
                    data-plasmic-name={"tab"}
                    data-plasmic-override={overrides.tab}
                    className={classNames(projectcss.all, sty.tab)}
                  >
                    <div
                      data-plasmic-name={"title3"}
                      data-plasmic-override={overrides.title3}
                      className={classNames(projectcss.all, sty.title3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fIcgK
                        )}
                      >
                        {"Options"}
                      </div>
                      <Icon7Icon
                        className={classNames(projectcss.all, sty.svg__eH6GM)}
                        role={"img"}
                      />
                    </div>
                    <div
                      data-plasmic-name={"options"}
                      data-plasmic-override={overrides.options}
                      className={classNames(projectcss.all, sty.options)}
                    >
                      <div
                        data-plasmic-name={"_7"}
                        data-plasmic-override={overrides._7}
                        className={classNames(projectcss.all, sty._7)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xqRc7
                          )}
                        >
                          {"Floorplans"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"_8"}
                        data-plasmic-override={overrides._8}
                        className={classNames(projectcss.all, sty._8)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__bbpur
                          )}
                        >
                          {"3D walkthrough"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"_9"}
                        data-plasmic-override={overrides._9}
                        className={classNames(projectcss.all, sty._9)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__a9EJv
                          )}
                        >
                          {"Smart features"}
                        </div>
                      </div>
                    </div>
                    <button
                      data-plasmic-name={"button"}
                      data-plasmic-override={overrides.button}
                      className={classNames(
                        projectcss.all,
                        projectcss.button,
                        sty.button
                      )}
                      ref={ref => {
                        $refs["button"] = ref;
                      }}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jxvV
                        )}
                      >
                        {"Make Enquiry"}
                      </div>
                    </button>
                  </div>
                </div>
                <div
                  data-plasmic-name={"cards2"}
                  data-plasmic-override={overrides.cards2}
                  className={classNames(projectcss.all, sty.cards2)}
                >
                  <div
                    data-plasmic-name={"card2"}
                    data-plasmic-override={overrides.card2}
                    className={classNames(projectcss.all, sty.card2)}
                  >
                    <div
                      data-plasmic-name={"imageWithFallback2"}
                      data-plasmic-override={overrides.imageWithFallback2}
                      className={classNames(
                        projectcss.all,
                        sty.imageWithFallback2
                      )}
                    >
                      <PlasmicImg__
                        data-plasmic-name={"img"}
                        data-plasmic-override={overrides.img}
                        alt={""}
                        className={classNames(sty.img)}
                        displayHeight={"50px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"50px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/website_starter/images/downloadIcon.svg",
                          fullWidth: 50,
                          fullHeight: 50,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      data-plasmic-name={"viewMore2"}
                      data-plasmic-override={overrides.viewMore2}
                      className={classNames(projectcss.all, sty.viewMore2)}
                    >
                      <div
                        data-plasmic-name={"pagination2"}
                        data-plasmic-override={overrides.pagination2}
                        className={classNames(projectcss.all, sty.pagination2)}
                      >
                        <Arrow2Icon
                          className={classNames(projectcss.all, sty.svg__bxril)}
                          role={"img"}
                        />

                        <div
                          data-plasmic-name={"number2"}
                          data-plasmic-override={overrides.number2}
                          className={classNames(projectcss.all, sty.number2)}
                        >
                          <div
                            data-plasmic-name={"_10"}
                            data-plasmic-override={overrides._10}
                            className={classNames(projectcss.all, sty._10)}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__ayNnS
                                )}
                              >
                                {"1"}
                              </div>
                            ) : null}
                          </div>
                          <div
                            data-plasmic-name={"_11"}
                            data-plasmic-override={overrides._11}
                            className={classNames(projectcss.all, sty._11)}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__pIbCk
                                )}
                              >
                                {"2"}
                              </div>
                            ) : null}
                          </div>
                          <div
                            data-plasmic-name={"_12"}
                            data-plasmic-override={overrides._12}
                            className={classNames(projectcss.all, sty._12)}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__mokr3
                                )}
                              >
                                {"3"}
                              </div>
                            ) : null}
                          </div>
                          <div
                            data-plasmic-name={"_13"}
                            data-plasmic-override={overrides._13}
                            className={classNames(projectcss.all, sty._13)}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__gi45P
                                )}
                              >
                                {"3"}
                              </div>
                            ) : null}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"freeBox"}
                          data-plasmic-override={overrides.freeBox}
                          className={classNames(projectcss.all, sty.freeBox)}
                        >
                          <ArrowIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__r8Ap
                            )}
                            role={"img"}
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "floorplans",
    "halfBg3",
    "results2",
    "title2",
    "badge2",
    "content",
    "tabs",
    "tab",
    "title3",
    "options",
    "_7",
    "_8",
    "_9",
    "button",
    "cards2",
    "card2",
    "imageWithFallback2",
    "img",
    "viewMore2",
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13",
    "freeBox"
  ],
  floorplans: [
    "floorplans",
    "halfBg3",
    "results2",
    "title2",
    "badge2",
    "content",
    "tabs",
    "tab",
    "title3",
    "options",
    "_7",
    "_8",
    "_9",
    "button",
    "cards2",
    "card2",
    "imageWithFallback2",
    "img",
    "viewMore2",
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13",
    "freeBox"
  ],
  halfBg3: ["halfBg3"],
  results2: [
    "results2",
    "title2",
    "badge2",
    "content",
    "tabs",
    "tab",
    "title3",
    "options",
    "_7",
    "_8",
    "_9",
    "button",
    "cards2",
    "card2",
    "imageWithFallback2",
    "img",
    "viewMore2",
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13",
    "freeBox"
  ],
  title2: ["title2", "badge2"],
  badge2: ["badge2"],
  content: [
    "content",
    "tabs",
    "tab",
    "title3",
    "options",
    "_7",
    "_8",
    "_9",
    "button",
    "cards2",
    "card2",
    "imageWithFallback2",
    "img",
    "viewMore2",
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13",
    "freeBox"
  ],
  tabs: ["tabs", "tab", "title3", "options", "_7", "_8", "_9", "button"],
  tab: ["tab", "title3", "options", "_7", "_8", "_9", "button"],
  title3: ["title3"],
  options: ["options", "_7", "_8", "_9"],
  _7: ["_7"],
  _8: ["_8"],
  _9: ["_9"],
  button: ["button"],
  cards2: [
    "cards2",
    "card2",
    "imageWithFallback2",
    "img",
    "viewMore2",
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13",
    "freeBox"
  ],
  card2: [
    "card2",
    "imageWithFallback2",
    "img",
    "viewMore2",
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13",
    "freeBox"
  ],
  imageWithFallback2: ["imageWithFallback2", "img"],
  img: ["img"],
  viewMore2: [
    "viewMore2",
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13",
    "freeBox"
  ],
  pagination2: [
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13",
    "freeBox"
  ],
  number2: ["number2", "_10", "_11", "_12", "_13"],
  _10: ["_10"],
  _11: ["_11"],
  _12: ["_12"],
  _13: ["_13"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  floorplans: "div";
  halfBg3: "div";
  results2: "div";
  title2: "div";
  badge2: "div";
  content: "div";
  tabs: "div";
  tab: "div";
  title3: "div";
  options: "div";
  _7: "div";
  _8: "div";
  _9: "div";
  button: "button";
  cards2: "div";
  card2: "div";
  imageWithFallback2: "div";
  img: typeof PlasmicImg__;
  viewMore2: "div";
  pagination2: "div";
  number2: "div";
  _10: "div";
  _11: "div";
  _12: "div";
  _13: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFloorplans__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFloorplans__VariantsArgs;
    args?: PlasmicFloorplans__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicFloorplans__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicFloorplans__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFloorplans__ArgProps,
          internalVariantPropNames: PlasmicFloorplans__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFloorplans__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFloorplans";
  } else {
    func.displayName = `PlasmicFloorplans.${nodeName}`;
  }
  return func;
}

export const PlasmicFloorplans = Object.assign(
  // Top-level PlasmicFloorplans renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    floorplans: makeNodeComponent("floorplans"),
    halfBg3: makeNodeComponent("halfBg3"),
    results2: makeNodeComponent("results2"),
    title2: makeNodeComponent("title2"),
    badge2: makeNodeComponent("badge2"),
    content: makeNodeComponent("content"),
    tabs: makeNodeComponent("tabs"),
    tab: makeNodeComponent("tab"),
    title3: makeNodeComponent("title3"),
    options: makeNodeComponent("options"),
    _7: makeNodeComponent("_7"),
    _8: makeNodeComponent("_8"),
    _9: makeNodeComponent("_9"),
    button: makeNodeComponent("button"),
    cards2: makeNodeComponent("cards2"),
    card2: makeNodeComponent("card2"),
    imageWithFallback2: makeNodeComponent("imageWithFallback2"),
    img: makeNodeComponent("img"),
    viewMore2: makeNodeComponent("viewMore2"),
    pagination2: makeNodeComponent("pagination2"),
    number2: makeNodeComponent("number2"),
    _10: makeNodeComponent("_10"),
    _11: makeNodeComponent("_11"),
    _12: makeNodeComponent("_12"),
    _13: makeNodeComponent("_13"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicFloorplans
    internalVariantProps: PlasmicFloorplans__VariantProps,
    internalArgProps: PlasmicFloorplans__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicFloorplans;
/* prettier-ignore-end */
