/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: onkH1pA6HdPM1JMb3Mte45
// Component: XYicFfLFhSQy

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/projectcss
import sty from "./PlasmicDevelopmentDetails.module.css"; // plasmic-import: XYicFfLFhSQy/css

import VideoIconIcon from "./icons/PlasmicIcon__VideoIcon"; // plasmic-import: fU6GnhOqexbr/icon
import Vector1Icon from "./icons/PlasmicIcon__Vector1"; // plasmic-import: f68eVSSD6GHl/icon
import Arrow2Icon from "./icons/PlasmicIcon__Arrow2"; // plasmic-import: SXieq0M2bzak/icon
import ArrowIcon from "./icons/PlasmicIcon__Arrow"; // plasmic-import: LrzIpY4AIRk_/icon
import Vector3Icon from "./icons/PlasmicIcon__Vector3"; // plasmic-import: FXwN8v7ffwYj/icon
import Icon7Icon from "./icons/PlasmicIcon__Icon7"; // plasmic-import: 6qGWRE-38yD0/icon
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: qv54e3PPyRr3/icon

createPlasmicElementProxy;

export type PlasmicDevelopmentDetails__VariantMembers = {};
export type PlasmicDevelopmentDetails__VariantsArgs = {};
type VariantPropType = keyof PlasmicDevelopmentDetails__VariantsArgs;
export const PlasmicDevelopmentDetails__VariantProps =
  new Array<VariantPropType>();

export type PlasmicDevelopmentDetails__ArgsType = {};
type ArgPropType = keyof PlasmicDevelopmentDetails__ArgsType;
export const PlasmicDevelopmentDetails__ArgProps = new Array<ArgPropType>();

export type PlasmicDevelopmentDetails__OverridesType = {
  root?: Flex__<"div">;
  developmentDetailsPage?: Flex__<"div">;
  headerHeroSection?: Flex__<"div">;
  heroSection?: Flex__<"div">;
  container?: Flex__<"div">;
  highlight1?: Flex__<"div">;
  halfBg?: Flex__<"div">;
  halfBg2?: Flex__<"div">;
  results?: Flex__<"div">;
  title?: Flex__<"div">;
  badge?: Flex__<"div">;
  cards?: Flex__<"div">;
  card?: Flex__<"div">;
  imageWithFallback?: Flex__<"div">;
  viewMore?: Flex__<"div">;
  pagination?: Flex__<"div">;
  number?: Flex__<"div">;
  _1?: Flex__<"div">;
  _2?: Flex__<"div">;
  _3?: Flex__<"div">;
  _4?: Flex__<"div">;
  description?: Flex__<"div">;
  text?: Flex__<"div">;
  _5?: Flex__<"div">;
  location?: Flex__<"div">;
  _6?: Flex__<"div">;
  footer?: Flex__<"div">;
  container2?: Flex__<"div">;
  left?: Flex__<"div">;
  logo?: Flex__<"div">;
  logo2?: Flex__<"div">;
  logoMark?: Flex__<"div">;
  texts?: Flex__<"div">;
  paragraph?: Flex__<"div">;
  paragraph2?: Flex__<"div">;
  right?: Flex__<"div">;
  container3?: Flex__<"div">;
  header?: Flex__<"div">;
  list?: Flex__<"div">;
  listItem?: Flex__<"div">;
  link?: Flex__<"div">;
  listItem2?: Flex__<"div">;
  link2?: Flex__<"div">;
  listItem3?: Flex__<"div">;
  link3?: Flex__<"div">;
  listItem4?: Flex__<"div">;
  link4?: Flex__<"div">;
  container4?: Flex__<"div">;
  header2?: Flex__<"div">;
  list2?: Flex__<"div">;
  listItem5?: Flex__<"div">;
  listItem6?: Flex__<"div">;
  container5?: Flex__<"div">;
  link5?: Flex__<"div">;
  link6?: Flex__<"div">;
  link7?: Flex__<"div">;
  container6?: Flex__<"div">;
  container7?: Flex__<"div">;
  paragraph3?: Flex__<"div">;
  _2025HouseNo5ByAfriNestAllRightsReserve?: Flex__<"div">;
  container8?: Flex__<"div">;
  text2?: Flex__<"div">;
  link8?: Flex__<"div">;
  link9?: Flex__<"div">;
  link10?: Flex__<"div">;
  floorplans?: Flex__<"div">;
  halfBg3?: Flex__<"div">;
  results2?: Flex__<"div">;
  title2?: Flex__<"div">;
  badge2?: Flex__<"div">;
  content?: Flex__<"div">;
  tabs?: Flex__<"div">;
  tab?: Flex__<"div">;
  title3?: Flex__<"div">;
  options?: Flex__<"div">;
  _7?: Flex__<"div">;
  _8?: Flex__<"div">;
  _9?: Flex__<"div">;
  button?: Flex__<"button">;
  cards2?: Flex__<"div">;
  card2?: Flex__<"div">;
  imageWithFallback2?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  viewMore2?: Flex__<"div">;
  pagination2?: Flex__<"div">;
  number2?: Flex__<"div">;
  _10?: Flex__<"div">;
  _11?: Flex__<"div">;
  _12?: Flex__<"div">;
  _13?: Flex__<"div">;
  floorplans2?: Flex__<"div">;
  card3?: Flex__<"div">;
  contactPage?: Flex__<"div">;
  heading3?: Flex__<"div">;
  paragraph4?: Flex__<"div">;
};

export interface DefaultDevelopmentDetailsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDevelopmentDetails__RenderFunc(props: {
  variants: PlasmicDevelopmentDetails__VariantsArgs;
  args: PlasmicDevelopmentDetails__ArgsType;
  overrides: PlasmicDevelopmentDetails__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"developmentDetailsPage"}
            data-plasmic-override={overrides.developmentDetailsPage}
            className={classNames(projectcss.all, sty.developmentDetailsPage)}
          >
            <div
              data-plasmic-name={"headerHeroSection"}
              data-plasmic-override={overrides.headerHeroSection}
              className={classNames(projectcss.all, sty.headerHeroSection)}
            >
              <div
                data-plasmic-name={"heroSection"}
                data-plasmic-override={overrides.heroSection}
                className={classNames(projectcss.all, sty.heroSection)}
              >
                <div
                  data-plasmic-name={"container"}
                  data-plasmic-override={overrides.container}
                  className={classNames(projectcss.all, sty.container)}
                >
                  <VideoIconIcon
                    className={classNames(projectcss.all, sty.svg__lzHiz)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gYs5
                    )}
                  >
                    {"Jahi Luxury Flats by House No. 5"}
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"highlight1"}
              data-plasmic-override={overrides.highlight1}
              className={classNames(projectcss.all, sty.highlight1)}
            >
              <div
                data-plasmic-name={"halfBg"}
                data-plasmic-override={overrides.halfBg}
                className={classNames(projectcss.all, sty.halfBg)}
              />

              <div
                data-plasmic-name={"halfBg2"}
                data-plasmic-override={overrides.halfBg2}
                className={classNames(projectcss.all, sty.halfBg2)}
              />

              <div
                data-plasmic-name={"results"}
                data-plasmic-override={overrides.results}
                className={classNames(projectcss.all, sty.results)}
              >
                <div
                  data-plasmic-name={"title"}
                  data-plasmic-override={overrides.title}
                  className={classNames(projectcss.all, sty.title)}
                >
                  <div
                    data-plasmic-name={"badge"}
                    data-plasmic-override={overrides.badge}
                    className={classNames(projectcss.all, sty.badge)}
                  >
                    <Vector1Icon
                      className={classNames(projectcss.all, sty.svg___56V4G)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uwYtP
                      )}
                    >
                      {"Smart | Green | Mid-Luxury Living"}
                    </div>
                  </div>
                  {false ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pdSbP
                      )}
                    >
                      {"Nigeria Developments"}
                    </div>
                  ) : null}
                </div>
                <div
                  data-plasmic-name={"cards"}
                  data-plasmic-override={overrides.cards}
                  className={classNames(projectcss.all, sty.cards)}
                >
                  <div
                    data-plasmic-name={"card"}
                    data-plasmic-override={overrides.card}
                    className={classNames(projectcss.all, sty.card)}
                  >
                    <div
                      data-plasmic-name={"imageWithFallback"}
                      data-plasmic-override={overrides.imageWithFallback}
                      className={classNames(
                        projectcss.all,
                        sty.imageWithFallback
                      )}
                    />

                    <div
                      data-plasmic-name={"viewMore"}
                      data-plasmic-override={overrides.viewMore}
                      className={classNames(projectcss.all, sty.viewMore)}
                    >
                      <div
                        data-plasmic-name={"pagination"}
                        data-plasmic-override={overrides.pagination}
                        className={classNames(projectcss.all, sty.pagination)}
                      >
                        <Arrow2Icon
                          className={classNames(projectcss.all, sty.svg__kilGk)}
                          role={"img"}
                        />

                        <div
                          data-plasmic-name={"number"}
                          data-plasmic-override={overrides.number}
                          className={classNames(projectcss.all, sty.number)}
                        >
                          <div
                            data-plasmic-name={"_1"}
                            data-plasmic-override={overrides._1}
                            className={classNames(projectcss.all, sty._1)}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__bFSj3
                                )}
                              >
                                {"1"}
                              </div>
                            ) : null}
                          </div>
                          <div
                            data-plasmic-name={"_2"}
                            data-plasmic-override={overrides._2}
                            className={classNames(projectcss.all, sty._2)}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__vdV3R
                                )}
                              >
                                {"2"}
                              </div>
                            ) : null}
                          </div>
                          <div
                            data-plasmic-name={"_3"}
                            data-plasmic-override={overrides._3}
                            className={classNames(projectcss.all, sty._3)}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__onj08
                                )}
                              >
                                {"3"}
                              </div>
                            ) : null}
                          </div>
                          <div
                            data-plasmic-name={"_4"}
                            data-plasmic-override={overrides._4}
                            className={classNames(projectcss.all, sty._4)}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__jNeYx
                                )}
                              >
                                {"3"}
                              </div>
                            ) : null}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__odH2K
                          )}
                        >
                          <ArrowIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___7Rsa3
                            )}
                            role={"img"}
                          />
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"description"}
                      data-plasmic-override={overrides.description}
                      className={classNames(projectcss.all, sty.description)}
                    >
                      <div
                        data-plasmic-name={"text"}
                        data-plasmic-override={overrides.text}
                        className={classNames(projectcss.all, sty.text)}
                      >
                        <div
                          data-plasmic-name={"_5"}
                          data-plasmic-override={overrides._5}
                          className={classNames(projectcss.all, sty._5)}
                        >
                          <div
                            data-plasmic-name={"location"}
                            data-plasmic-override={overrides.location}
                            className={classNames(projectcss.all, sty.location)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__kiYos
                              )}
                            >
                              {"Project Highlights"}
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"_6"}
                            data-plasmic-override={overrides._6}
                            className={classNames(projectcss.all, sty._6)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__yiyKn
                              )}
                            >
                              {
                                "300 Smart Flats\n9 Floors\n1\u20133 Bedroom Units\nSolar power + EV charging\nCentral water purification\nCommunity workspace + fitness studio\n24/7 smart security"
                              }
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(projectcss.all, sty.footer)}
            >
              <div
                data-plasmic-name={"container2"}
                data-plasmic-override={overrides.container2}
                className={classNames(projectcss.all, sty.container2)}
              >
                <div
                  data-plasmic-name={"left"}
                  data-plasmic-override={overrides.left}
                  className={classNames(projectcss.all, sty.left)}
                >
                  <div
                    data-plasmic-name={"logo"}
                    data-plasmic-override={overrides.logo}
                    className={classNames(projectcss.all, sty.logo)}
                  >
                    <div
                      data-plasmic-name={"logo2"}
                      data-plasmic-override={overrides.logo2}
                      className={classNames(projectcss.all, sty.logo2)}
                    >
                      <div
                        data-plasmic-name={"logoMark"}
                        data-plasmic-override={overrides.logoMark}
                        className={classNames(projectcss.all, sty.logoMark)}
                      >
                        <Vector3Icon
                          className={classNames(projectcss.all, sty.svg__pmBo7)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wqYa0
                          )}
                        >
                          {"5"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fWupG
                        )}
                      >
                        {"HOUSE NO. 5"}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"texts"}
                    data-plasmic-override={overrides.texts}
                    className={classNames(projectcss.all, sty.texts)}
                  >
                    <div
                      data-plasmic-name={"paragraph"}
                      data-plasmic-override={overrides.paragraph}
                      className={classNames(projectcss.all, sty.paragraph)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uLwwd
                        )}
                      >
                        {"Elegant. Sustainable. African."}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"paragraph2"}
                      data-plasmic-override={overrides.paragraph2}
                      className={classNames(projectcss.all, sty.paragraph2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qVfvU
                        )}
                      >
                        {"Premium smart city developments across Africa."}
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"right"}
                  data-plasmic-override={overrides.right}
                  className={classNames(projectcss.all, sty.right)}
                >
                  <div
                    data-plasmic-name={"container3"}
                    data-plasmic-override={overrides.container3}
                    className={classNames(projectcss.all, sty.container3)}
                  >
                    <div
                      data-plasmic-name={"header"}
                      data-plasmic-override={overrides.header}
                      className={classNames(projectcss.all, sty.header)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mkmDd
                        )}
                      >
                        {"Quick Links"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"list"}
                      data-plasmic-override={overrides.list}
                      className={classNames(projectcss.all, sty.list)}
                    >
                      <div
                        data-plasmic-name={"listItem"}
                        data-plasmic-override={overrides.listItem}
                        className={classNames(projectcss.all, sty.listItem)}
                      >
                        <div
                          data-plasmic-name={"link"}
                          data-plasmic-override={overrides.link}
                          className={classNames(projectcss.all, sty.link)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__e118G
                            )}
                          >
                            {"Browse Estates"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"listItem2"}
                        data-plasmic-override={overrides.listItem2}
                        className={classNames(projectcss.all, sty.listItem2)}
                      >
                        <div
                          data-plasmic-name={"link2"}
                          data-plasmic-override={overrides.link2}
                          className={classNames(projectcss.all, sty.link2)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__l5QUc
                            )}
                          >
                            {"About Us"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"listItem3"}
                        data-plasmic-override={overrides.listItem3}
                        className={classNames(projectcss.all, sty.listItem3)}
                      >
                        <div
                          data-plasmic-name={"link3"}
                          data-plasmic-override={overrides.link3}
                          className={classNames(projectcss.all, sty.link3)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__imMer
                            )}
                          >
                            {"Smart Living"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"listItem4"}
                        data-plasmic-override={overrides.listItem4}
                        className={classNames(projectcss.all, sty.listItem4)}
                      >
                        <div
                          data-plasmic-name={"link4"}
                          data-plasmic-override={overrides.link4}
                          className={classNames(projectcss.all, sty.link4)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__sBbZ
                            )}
                          >
                            {"Contact"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"container4"}
                    data-plasmic-override={overrides.container4}
                    className={classNames(projectcss.all, sty.container4)}
                  >
                    <div
                      data-plasmic-name={"header2"}
                      data-plasmic-override={overrides.header2}
                      className={classNames(projectcss.all, sty.header2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__p5754
                        )}
                      >
                        {"Connect"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"list2"}
                      data-plasmic-override={overrides.list2}
                      className={classNames(projectcss.all, sty.list2)}
                    >
                      <div
                        data-plasmic-name={"listItem5"}
                        data-plasmic-override={overrides.listItem5}
                        className={classNames(projectcss.all, sty.listItem5)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__mx98R
                          )}
                        >
                          {"info@houseno5.com"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"listItem6"}
                        data-plasmic-override={overrides.listItem6}
                        className={classNames(projectcss.all, sty.listItem6)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__v55Ps
                          )}
                        >
                          {"+1 (555) 123-4567"}
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"container5"}
                      data-plasmic-override={overrides.container5}
                      className={classNames(projectcss.all, sty.container5)}
                    >
                      <div
                        data-plasmic-name={"link5"}
                        data-plasmic-override={overrides.link5}
                        className={classNames(projectcss.all, sty.link5)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__uPfgL
                          )}
                        >
                          {"LinkedIn"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"link6"}
                        data-plasmic-override={overrides.link6}
                        className={classNames(projectcss.all, sty.link6)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__h73A
                          )}
                        >
                          {"Instagram"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"link7"}
                        data-plasmic-override={overrides.link7}
                        className={classNames(projectcss.all, sty.link7)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__m22Ez
                          )}
                        >
                          {"Twitter"}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"container6"}
                data-plasmic-override={overrides.container6}
                className={classNames(projectcss.all, sty.container6)}
              >
                <div
                  data-plasmic-name={"container7"}
                  data-plasmic-override={overrides.container7}
                  className={classNames(projectcss.all, sty.container7)}
                >
                  <div
                    data-plasmic-name={"paragraph3"}
                    data-plasmic-override={overrides.paragraph3}
                    className={classNames(projectcss.all, sty.paragraph3)}
                  >
                    <div
                      data-plasmic-name={
                        "_2025HouseNo5ByAfriNestAllRightsReserve"
                      }
                      data-plasmic-override={
                        overrides._2025HouseNo5ByAfriNestAllRightsReserve
                      }
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty._2025HouseNo5ByAfriNestAllRightsReserve
                      )}
                    >
                      {
                        "\u00a9 2025 House No. 5 by AfriNest. All rights reserved."
                      }
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"container8"}
                    data-plasmic-override={overrides.container8}
                    className={classNames(projectcss.all, sty.container8)}
                  >
                    <div
                      data-plasmic-name={"text2"}
                      data-plasmic-override={overrides.text2}
                      className={classNames(projectcss.all, sty.text2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vGdT
                        )}
                      >
                        {"Sister Brands:"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"link8"}
                      data-plasmic-override={overrides.link8}
                      className={classNames(projectcss.all, sty.link8)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__h0MbW
                        )}
                      >
                        {"AfriNest"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"link9"}
                      data-plasmic-override={overrides.link9}
                      className={classNames(projectcss.all, sty.link9)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ogYHl
                        )}
                      >
                        {"Urban Edge"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"link10"}
                      data-plasmic-override={overrides.link10}
                      className={classNames(projectcss.all, sty.link10)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vxLv
                        )}
                      >
                        {"Green Haven"}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"floorplans"}
              data-plasmic-override={overrides.floorplans}
              className={classNames(projectcss.all, sty.floorplans)}
            >
              <div
                data-plasmic-name={"halfBg3"}
                data-plasmic-override={overrides.halfBg3}
                className={classNames(projectcss.all, sty.halfBg3)}
              />

              <div
                data-plasmic-name={"results2"}
                data-plasmic-override={overrides.results2}
                className={classNames(projectcss.all, sty.results2)}
              >
                <div
                  data-plasmic-name={"title2"}
                  data-plasmic-override={overrides.title2}
                  className={classNames(projectcss.all, sty.title2)}
                >
                  <div
                    data-plasmic-name={"badge2"}
                    data-plasmic-override={overrides.badge2}
                    className={classNames(projectcss.all, sty.badge2)}
                  >
                    <Vector1Icon
                      className={classNames(projectcss.all, sty.svg__lqyS)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__za1Nz
                      )}
                    >
                      {"Floorplans + 3D Walkthroughs"}
                    </div>
                  </div>
                  {false ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___888M
                      )}
                    >
                      {"Nigeria Developments"}
                    </div>
                  ) : null}
                </div>
                <div
                  data-plasmic-name={"content"}
                  data-plasmic-override={overrides.content}
                  className={classNames(projectcss.all, sty.content)}
                >
                  <div
                    data-plasmic-name={"tabs"}
                    data-plasmic-override={overrides.tabs}
                    className={classNames(projectcss.all, sty.tabs)}
                  >
                    <div
                      data-plasmic-name={"tab"}
                      data-plasmic-override={overrides.tab}
                      className={classNames(projectcss.all, sty.tab)}
                    >
                      <div
                        data-plasmic-name={"title3"}
                        data-plasmic-override={overrides.title3}
                        className={classNames(projectcss.all, sty.title3)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vivXf
                          )}
                        >
                          {"Options"}
                        </div>
                        <Icon7Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___6JzbQ
                          )}
                          role={"img"}
                        />
                      </div>
                      <div
                        data-plasmic-name={"options"}
                        data-plasmic-override={overrides.options}
                        className={classNames(projectcss.all, sty.options)}
                      >
                        <div
                          data-plasmic-name={"_7"}
                          data-plasmic-override={overrides._7}
                          className={classNames(projectcss.all, sty._7)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__eWbZr
                            )}
                          >
                            {"Floorplans"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"_8"}
                          data-plasmic-override={overrides._8}
                          className={classNames(projectcss.all, sty._8)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__fDxrQ
                            )}
                          >
                            {"3D walkthrough"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"_9"}
                          data-plasmic-override={overrides._9}
                          className={classNames(projectcss.all, sty._9)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__kznWw
                            )}
                          >
                            {"Smart features"}
                          </div>
                        </div>
                      </div>
                      <button
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        className={classNames(
                          projectcss.all,
                          projectcss.button,
                          sty.button
                        )}
                        ref={ref => {
                          $refs["button"] = ref;
                        }}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__eVri
                          )}
                        >
                          {"Make Enquiry"}
                        </div>
                      </button>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"cards2"}
                    data-plasmic-override={overrides.cards2}
                    className={classNames(projectcss.all, sty.cards2)}
                  >
                    <div
                      data-plasmic-name={"card2"}
                      data-plasmic-override={overrides.card2}
                      className={classNames(projectcss.all, sty.card2)}
                    >
                      <div
                        data-plasmic-name={"imageWithFallback2"}
                        data-plasmic-override={overrides.imageWithFallback2}
                        className={classNames(
                          projectcss.all,
                          sty.imageWithFallback2
                        )}
                      >
                        <PlasmicImg__
                          data-plasmic-name={"img"}
                          data-plasmic-override={overrides.img}
                          alt={""}
                          className={classNames(sty.img)}
                          displayHeight={"50px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"50px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/website_starter/images/downloadIcon.svg",
                            fullWidth: 50,
                            fullHeight: 50,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        data-plasmic-name={"viewMore2"}
                        data-plasmic-override={overrides.viewMore2}
                        className={classNames(projectcss.all, sty.viewMore2)}
                      >
                        <div
                          data-plasmic-name={"pagination2"}
                          data-plasmic-override={overrides.pagination2}
                          className={classNames(
                            projectcss.all,
                            sty.pagination2
                          )}
                        >
                          <Arrow2Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__b6Dyb
                            )}
                            role={"img"}
                          />

                          <div
                            data-plasmic-name={"number2"}
                            data-plasmic-override={overrides.number2}
                            className={classNames(projectcss.all, sty.number2)}
                          >
                            <div
                              data-plasmic-name={"_10"}
                              data-plasmic-override={overrides._10}
                              className={classNames(projectcss.all, sty._10)}
                            >
                              {false ? (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__jxOoE
                                  )}
                                >
                                  {"1"}
                                </div>
                              ) : null}
                            </div>
                            <div
                              data-plasmic-name={"_11"}
                              data-plasmic-override={overrides._11}
                              className={classNames(projectcss.all, sty._11)}
                            >
                              {false ? (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__tueS0
                                  )}
                                >
                                  {"2"}
                                </div>
                              ) : null}
                            </div>
                            <div
                              data-plasmic-name={"_12"}
                              data-plasmic-override={overrides._12}
                              className={classNames(projectcss.all, sty._12)}
                            >
                              {false ? (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__bOeAy
                                  )}
                                >
                                  {"3"}
                                </div>
                              ) : null}
                            </div>
                            <div
                              data-plasmic-name={"_13"}
                              data-plasmic-override={overrides._13}
                              className={classNames(projectcss.all, sty._13)}
                            >
                              {false ? (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___0Rnjc
                                  )}
                                >
                                  {"3"}
                                </div>
                              ) : null}
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__bIjgc
                            )}
                          >
                            <ArrowIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__fQ6Hr
                              )}
                              role={"img"}
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"floorplans2"}
              data-plasmic-override={overrides.floorplans2}
              className={classNames(projectcss.all, sty.floorplans2)}
            >
              <div
                data-plasmic-name={"card3"}
                data-plasmic-override={overrides.card3}
                className={classNames(projectcss.all, sty.card3)}
              >
                <div
                  data-plasmic-name={"contactPage"}
                  data-plasmic-override={overrides.contactPage}
                  className={classNames(projectcss.all, sty.contactPage)}
                >
                  <Icon14Icon
                    className={classNames(projectcss.all, sty.svg___9A7Di)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"heading3"}
                    data-plasmic-override={overrides.heading3}
                    className={classNames(projectcss.all, sty.heading3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jrm4
                      )}
                    >
                      {"Interactive Map"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"paragraph4"}
                    data-plasmic-override={overrides.paragraph4}
                    className={classNames(projectcss.all, sty.paragraph4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hTmgy
                      )}
                    >
                      {"Map showing building locations would appear here"}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "developmentDetailsPage",
    "headerHeroSection",
    "heroSection",
    "container",
    "highlight1",
    "halfBg",
    "halfBg2",
    "results",
    "title",
    "badge",
    "cards",
    "card",
    "imageWithFallback",
    "viewMore",
    "pagination",
    "number",
    "_1",
    "_2",
    "_3",
    "_4",
    "description",
    "text",
    "_5",
    "location",
    "_6",
    "footer",
    "container2",
    "left",
    "logo",
    "logo2",
    "logoMark",
    "texts",
    "paragraph",
    "paragraph2",
    "right",
    "container3",
    "header",
    "list",
    "listItem",
    "link",
    "listItem2",
    "link2",
    "listItem3",
    "link3",
    "listItem4",
    "link4",
    "container4",
    "header2",
    "list2",
    "listItem5",
    "listItem6",
    "container5",
    "link5",
    "link6",
    "link7",
    "container6",
    "container7",
    "paragraph3",
    "_2025HouseNo5ByAfriNestAllRightsReserve",
    "container8",
    "text2",
    "link8",
    "link9",
    "link10",
    "floorplans",
    "halfBg3",
    "results2",
    "title2",
    "badge2",
    "content",
    "tabs",
    "tab",
    "title3",
    "options",
    "_7",
    "_8",
    "_9",
    "button",
    "cards2",
    "card2",
    "imageWithFallback2",
    "img",
    "viewMore2",
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13",
    "floorplans2",
    "card3",
    "contactPage",
    "heading3",
    "paragraph4"
  ],
  developmentDetailsPage: [
    "developmentDetailsPage",
    "headerHeroSection",
    "heroSection",
    "container",
    "highlight1",
    "halfBg",
    "halfBg2",
    "results",
    "title",
    "badge",
    "cards",
    "card",
    "imageWithFallback",
    "viewMore",
    "pagination",
    "number",
    "_1",
    "_2",
    "_3",
    "_4",
    "description",
    "text",
    "_5",
    "location",
    "_6",
    "footer",
    "container2",
    "left",
    "logo",
    "logo2",
    "logoMark",
    "texts",
    "paragraph",
    "paragraph2",
    "right",
    "container3",
    "header",
    "list",
    "listItem",
    "link",
    "listItem2",
    "link2",
    "listItem3",
    "link3",
    "listItem4",
    "link4",
    "container4",
    "header2",
    "list2",
    "listItem5",
    "listItem6",
    "container5",
    "link5",
    "link6",
    "link7",
    "container6",
    "container7",
    "paragraph3",
    "_2025HouseNo5ByAfriNestAllRightsReserve",
    "container8",
    "text2",
    "link8",
    "link9",
    "link10",
    "floorplans",
    "halfBg3",
    "results2",
    "title2",
    "badge2",
    "content",
    "tabs",
    "tab",
    "title3",
    "options",
    "_7",
    "_8",
    "_9",
    "button",
    "cards2",
    "card2",
    "imageWithFallback2",
    "img",
    "viewMore2",
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13",
    "floorplans2",
    "card3",
    "contactPage",
    "heading3",
    "paragraph4"
  ],
  headerHeroSection: ["headerHeroSection", "heroSection", "container"],
  heroSection: ["heroSection", "container"],
  container: ["container"],
  highlight1: [
    "highlight1",
    "halfBg",
    "halfBg2",
    "results",
    "title",
    "badge",
    "cards",
    "card",
    "imageWithFallback",
    "viewMore",
    "pagination",
    "number",
    "_1",
    "_2",
    "_3",
    "_4",
    "description",
    "text",
    "_5",
    "location",
    "_6"
  ],
  halfBg: ["halfBg"],
  halfBg2: ["halfBg2"],
  results: [
    "results",
    "title",
    "badge",
    "cards",
    "card",
    "imageWithFallback",
    "viewMore",
    "pagination",
    "number",
    "_1",
    "_2",
    "_3",
    "_4",
    "description",
    "text",
    "_5",
    "location",
    "_6"
  ],
  title: ["title", "badge"],
  badge: ["badge"],
  cards: [
    "cards",
    "card",
    "imageWithFallback",
    "viewMore",
    "pagination",
    "number",
    "_1",
    "_2",
    "_3",
    "_4",
    "description",
    "text",
    "_5",
    "location",
    "_6"
  ],
  card: [
    "card",
    "imageWithFallback",
    "viewMore",
    "pagination",
    "number",
    "_1",
    "_2",
    "_3",
    "_4",
    "description",
    "text",
    "_5",
    "location",
    "_6"
  ],
  imageWithFallback: ["imageWithFallback"],
  viewMore: ["viewMore", "pagination", "number", "_1", "_2", "_3", "_4"],
  pagination: ["pagination", "number", "_1", "_2", "_3", "_4"],
  number: ["number", "_1", "_2", "_3", "_4"],
  _1: ["_1"],
  _2: ["_2"],
  _3: ["_3"],
  _4: ["_4"],
  description: ["description", "text", "_5", "location", "_6"],
  text: ["text", "_5", "location", "_6"],
  _5: ["_5", "location", "_6"],
  location: ["location"],
  _6: ["_6"],
  footer: [
    "footer",
    "container2",
    "left",
    "logo",
    "logo2",
    "logoMark",
    "texts",
    "paragraph",
    "paragraph2",
    "right",
    "container3",
    "header",
    "list",
    "listItem",
    "link",
    "listItem2",
    "link2",
    "listItem3",
    "link3",
    "listItem4",
    "link4",
    "container4",
    "header2",
    "list2",
    "listItem5",
    "listItem6",
    "container5",
    "link5",
    "link6",
    "link7",
    "container6",
    "container7",
    "paragraph3",
    "_2025HouseNo5ByAfriNestAllRightsReserve",
    "container8",
    "text2",
    "link8",
    "link9",
    "link10"
  ],
  container2: [
    "container2",
    "left",
    "logo",
    "logo2",
    "logoMark",
    "texts",
    "paragraph",
    "paragraph2",
    "right",
    "container3",
    "header",
    "list",
    "listItem",
    "link",
    "listItem2",
    "link2",
    "listItem3",
    "link3",
    "listItem4",
    "link4",
    "container4",
    "header2",
    "list2",
    "listItem5",
    "listItem6",
    "container5",
    "link5",
    "link6",
    "link7"
  ],
  left: [
    "left",
    "logo",
    "logo2",
    "logoMark",
    "texts",
    "paragraph",
    "paragraph2"
  ],
  logo: ["logo", "logo2", "logoMark"],
  logo2: ["logo2", "logoMark"],
  logoMark: ["logoMark"],
  texts: ["texts", "paragraph", "paragraph2"],
  paragraph: ["paragraph"],
  paragraph2: ["paragraph2"],
  right: [
    "right",
    "container3",
    "header",
    "list",
    "listItem",
    "link",
    "listItem2",
    "link2",
    "listItem3",
    "link3",
    "listItem4",
    "link4",
    "container4",
    "header2",
    "list2",
    "listItem5",
    "listItem6",
    "container5",
    "link5",
    "link6",
    "link7"
  ],
  container3: [
    "container3",
    "header",
    "list",
    "listItem",
    "link",
    "listItem2",
    "link2",
    "listItem3",
    "link3",
    "listItem4",
    "link4"
  ],
  header: ["header"],
  list: [
    "list",
    "listItem",
    "link",
    "listItem2",
    "link2",
    "listItem3",
    "link3",
    "listItem4",
    "link4"
  ],
  listItem: ["listItem", "link"],
  link: ["link"],
  listItem2: ["listItem2", "link2"],
  link2: ["link2"],
  listItem3: ["listItem3", "link3"],
  link3: ["link3"],
  listItem4: ["listItem4", "link4"],
  link4: ["link4"],
  container4: [
    "container4",
    "header2",
    "list2",
    "listItem5",
    "listItem6",
    "container5",
    "link5",
    "link6",
    "link7"
  ],
  header2: ["header2"],
  list2: ["list2", "listItem5", "listItem6"],
  listItem5: ["listItem5"],
  listItem6: ["listItem6"],
  container5: ["container5", "link5", "link6", "link7"],
  link5: ["link5"],
  link6: ["link6"],
  link7: ["link7"],
  container6: [
    "container6",
    "container7",
    "paragraph3",
    "_2025HouseNo5ByAfriNestAllRightsReserve",
    "container8",
    "text2",
    "link8",
    "link9",
    "link10"
  ],
  container7: [
    "container7",
    "paragraph3",
    "_2025HouseNo5ByAfriNestAllRightsReserve",
    "container8",
    "text2",
    "link8",
    "link9",
    "link10"
  ],
  paragraph3: ["paragraph3", "_2025HouseNo5ByAfriNestAllRightsReserve"],
  _2025HouseNo5ByAfriNestAllRightsReserve: [
    "_2025HouseNo5ByAfriNestAllRightsReserve"
  ],
  container8: ["container8", "text2", "link8", "link9", "link10"],
  text2: ["text2"],
  link8: ["link8"],
  link9: ["link9"],
  link10: ["link10"],
  floorplans: [
    "floorplans",
    "halfBg3",
    "results2",
    "title2",
    "badge2",
    "content",
    "tabs",
    "tab",
    "title3",
    "options",
    "_7",
    "_8",
    "_9",
    "button",
    "cards2",
    "card2",
    "imageWithFallback2",
    "img",
    "viewMore2",
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13"
  ],
  halfBg3: ["halfBg3"],
  results2: [
    "results2",
    "title2",
    "badge2",
    "content",
    "tabs",
    "tab",
    "title3",
    "options",
    "_7",
    "_8",
    "_9",
    "button",
    "cards2",
    "card2",
    "imageWithFallback2",
    "img",
    "viewMore2",
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13"
  ],
  title2: ["title2", "badge2"],
  badge2: ["badge2"],
  content: [
    "content",
    "tabs",
    "tab",
    "title3",
    "options",
    "_7",
    "_8",
    "_9",
    "button",
    "cards2",
    "card2",
    "imageWithFallback2",
    "img",
    "viewMore2",
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13"
  ],
  tabs: ["tabs", "tab", "title3", "options", "_7", "_8", "_9", "button"],
  tab: ["tab", "title3", "options", "_7", "_8", "_9", "button"],
  title3: ["title3"],
  options: ["options", "_7", "_8", "_9"],
  _7: ["_7"],
  _8: ["_8"],
  _9: ["_9"],
  button: ["button"],
  cards2: [
    "cards2",
    "card2",
    "imageWithFallback2",
    "img",
    "viewMore2",
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13"
  ],
  card2: [
    "card2",
    "imageWithFallback2",
    "img",
    "viewMore2",
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13"
  ],
  imageWithFallback2: ["imageWithFallback2", "img"],
  img: ["img"],
  viewMore2: [
    "viewMore2",
    "pagination2",
    "number2",
    "_10",
    "_11",
    "_12",
    "_13"
  ],
  pagination2: ["pagination2", "number2", "_10", "_11", "_12", "_13"],
  number2: ["number2", "_10", "_11", "_12", "_13"],
  _10: ["_10"],
  _11: ["_11"],
  _12: ["_12"],
  _13: ["_13"],
  floorplans2: [
    "floorplans2",
    "card3",
    "contactPage",
    "heading3",
    "paragraph4"
  ],
  card3: ["card3", "contactPage", "heading3", "paragraph4"],
  contactPage: ["contactPage", "heading3", "paragraph4"],
  heading3: ["heading3"],
  paragraph4: ["paragraph4"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  developmentDetailsPage: "div";
  headerHeroSection: "div";
  heroSection: "div";
  container: "div";
  highlight1: "div";
  halfBg: "div";
  halfBg2: "div";
  results: "div";
  title: "div";
  badge: "div";
  cards: "div";
  card: "div";
  imageWithFallback: "div";
  viewMore: "div";
  pagination: "div";
  number: "div";
  _1: "div";
  _2: "div";
  _3: "div";
  _4: "div";
  description: "div";
  text: "div";
  _5: "div";
  location: "div";
  _6: "div";
  footer: "div";
  container2: "div";
  left: "div";
  logo: "div";
  logo2: "div";
  logoMark: "div";
  texts: "div";
  paragraph: "div";
  paragraph2: "div";
  right: "div";
  container3: "div";
  header: "div";
  list: "div";
  listItem: "div";
  link: "div";
  listItem2: "div";
  link2: "div";
  listItem3: "div";
  link3: "div";
  listItem4: "div";
  link4: "div";
  container4: "div";
  header2: "div";
  list2: "div";
  listItem5: "div";
  listItem6: "div";
  container5: "div";
  link5: "div";
  link6: "div";
  link7: "div";
  container6: "div";
  container7: "div";
  paragraph3: "div";
  _2025HouseNo5ByAfriNestAllRightsReserve: "div";
  container8: "div";
  text2: "div";
  link8: "div";
  link9: "div";
  link10: "div";
  floorplans: "div";
  halfBg3: "div";
  results2: "div";
  title2: "div";
  badge2: "div";
  content: "div";
  tabs: "div";
  tab: "div";
  title3: "div";
  options: "div";
  _7: "div";
  _8: "div";
  _9: "div";
  button: "button";
  cards2: "div";
  card2: "div";
  imageWithFallback2: "div";
  img: typeof PlasmicImg__;
  viewMore2: "div";
  pagination2: "div";
  number2: "div";
  _10: "div";
  _11: "div";
  _12: "div";
  _13: "div";
  floorplans2: "div";
  card3: "div";
  contactPage: "div";
  heading3: "div";
  paragraph4: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDevelopmentDetails__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDevelopmentDetails__VariantsArgs;
    args?: PlasmicDevelopmentDetails__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicDevelopmentDetails__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicDevelopmentDetails__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDevelopmentDetails__ArgProps,
          internalVariantPropNames: PlasmicDevelopmentDetails__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDevelopmentDetails__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDevelopmentDetails";
  } else {
    func.displayName = `PlasmicDevelopmentDetails.${nodeName}`;
  }
  return func;
}

export const PlasmicDevelopmentDetails = Object.assign(
  // Top-level PlasmicDevelopmentDetails renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    developmentDetailsPage: makeNodeComponent("developmentDetailsPage"),
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    heroSection: makeNodeComponent("heroSection"),
    container: makeNodeComponent("container"),
    highlight1: makeNodeComponent("highlight1"),
    halfBg: makeNodeComponent("halfBg"),
    halfBg2: makeNodeComponent("halfBg2"),
    results: makeNodeComponent("results"),
    title: makeNodeComponent("title"),
    badge: makeNodeComponent("badge"),
    cards: makeNodeComponent("cards"),
    card: makeNodeComponent("card"),
    imageWithFallback: makeNodeComponent("imageWithFallback"),
    viewMore: makeNodeComponent("viewMore"),
    pagination: makeNodeComponent("pagination"),
    number: makeNodeComponent("number"),
    _1: makeNodeComponent("_1"),
    _2: makeNodeComponent("_2"),
    _3: makeNodeComponent("_3"),
    _4: makeNodeComponent("_4"),
    description: makeNodeComponent("description"),
    text: makeNodeComponent("text"),
    _5: makeNodeComponent("_5"),
    location: makeNodeComponent("location"),
    _6: makeNodeComponent("_6"),
    footer: makeNodeComponent("footer"),
    container2: makeNodeComponent("container2"),
    left: makeNodeComponent("left"),
    logo: makeNodeComponent("logo"),
    logo2: makeNodeComponent("logo2"),
    logoMark: makeNodeComponent("logoMark"),
    texts: makeNodeComponent("texts"),
    paragraph: makeNodeComponent("paragraph"),
    paragraph2: makeNodeComponent("paragraph2"),
    right: makeNodeComponent("right"),
    container3: makeNodeComponent("container3"),
    header: makeNodeComponent("header"),
    list: makeNodeComponent("list"),
    listItem: makeNodeComponent("listItem"),
    link: makeNodeComponent("link"),
    listItem2: makeNodeComponent("listItem2"),
    link2: makeNodeComponent("link2"),
    listItem3: makeNodeComponent("listItem3"),
    link3: makeNodeComponent("link3"),
    listItem4: makeNodeComponent("listItem4"),
    link4: makeNodeComponent("link4"),
    container4: makeNodeComponent("container4"),
    header2: makeNodeComponent("header2"),
    list2: makeNodeComponent("list2"),
    listItem5: makeNodeComponent("listItem5"),
    listItem6: makeNodeComponent("listItem6"),
    container5: makeNodeComponent("container5"),
    link5: makeNodeComponent("link5"),
    link6: makeNodeComponent("link6"),
    link7: makeNodeComponent("link7"),
    container6: makeNodeComponent("container6"),
    container7: makeNodeComponent("container7"),
    paragraph3: makeNodeComponent("paragraph3"),
    _2025HouseNo5ByAfriNestAllRightsReserve: makeNodeComponent(
      "_2025HouseNo5ByAfriNestAllRightsReserve"
    ),
    container8: makeNodeComponent("container8"),
    text2: makeNodeComponent("text2"),
    link8: makeNodeComponent("link8"),
    link9: makeNodeComponent("link9"),
    link10: makeNodeComponent("link10"),
    floorplans: makeNodeComponent("floorplans"),
    halfBg3: makeNodeComponent("halfBg3"),
    results2: makeNodeComponent("results2"),
    title2: makeNodeComponent("title2"),
    badge2: makeNodeComponent("badge2"),
    content: makeNodeComponent("content"),
    tabs: makeNodeComponent("tabs"),
    tab: makeNodeComponent("tab"),
    title3: makeNodeComponent("title3"),
    options: makeNodeComponent("options"),
    _7: makeNodeComponent("_7"),
    _8: makeNodeComponent("_8"),
    _9: makeNodeComponent("_9"),
    button: makeNodeComponent("button"),
    cards2: makeNodeComponent("cards2"),
    card2: makeNodeComponent("card2"),
    imageWithFallback2: makeNodeComponent("imageWithFallback2"),
    img: makeNodeComponent("img"),
    viewMore2: makeNodeComponent("viewMore2"),
    pagination2: makeNodeComponent("pagination2"),
    number2: makeNodeComponent("number2"),
    _10: makeNodeComponent("_10"),
    _11: makeNodeComponent("_11"),
    _12: makeNodeComponent("_12"),
    _13: makeNodeComponent("_13"),
    floorplans2: makeNodeComponent("floorplans2"),
    card3: makeNodeComponent("card3"),
    contactPage: makeNodeComponent("contactPage"),
    heading3: makeNodeComponent("heading3"),
    paragraph4: makeNodeComponent("paragraph4"),

    // Metadata about props expected for PlasmicDevelopmentDetails
    internalVariantProps: PlasmicDevelopmentDetails__VariantProps,
    internalArgProps: PlasmicDevelopmentDetails__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicDevelopmentDetails;
/* prettier-ignore-end */
