/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: onkH1pA6HdPM1JMb3Mte45
// Component: tET3M_zrAIHt

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/projectcss
import sty from "./PlasmicContact.module.css"; // plasmic-import: tET3M_zrAIHt/css

import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: Dmi5ztWZ87DU/icon
import Icon9Icon from "./icons/PlasmicIcon__Icon9"; // plasmic-import: RuCz-orciNBL/icon
import Icon10Icon from "./icons/PlasmicIcon__Icon10"; // plasmic-import: lpqegJrHHVmg/icon
import Icon11Icon from "./icons/PlasmicIcon__Icon11"; // plasmic-import: RATZdlprq__j/icon
import Icon13Icon from "./icons/PlasmicIcon__Icon13"; // plasmic-import: RKR78U3oWnSC/icon
import Vector3Icon from "./icons/PlasmicIcon__Vector3"; // plasmic-import: FXwN8v7ffwYj/icon

createPlasmicElementProxy;

export type PlasmicContact__VariantMembers = {};
export type PlasmicContact__VariantsArgs = {};
type VariantPropType = keyof PlasmicContact__VariantsArgs;
export const PlasmicContact__VariantProps = new Array<VariantPropType>();

export type PlasmicContact__ArgsType = {};
type ArgPropType = keyof PlasmicContact__ArgsType;
export const PlasmicContact__ArgProps = new Array<ArgPropType>();

export type PlasmicContact__OverridesType = {
  root?: Flex__<"div">;
  contactPage?: Flex__<"div">;
  headerHeroSection?: Flex__<"div">;
  header?: Flex__<"div">;
  container?: Flex__<"div">;
  logo?: Flex__<"div">;
  logoMark?: Flex__<"div">;
  navigationMenu?: Flex__<"div">;
  link?: Flex__<"div">;
  link2?: Flex__<"div">;
  link3?: Flex__<"div">;
  link4?: Flex__<"div">;
  link5?: Flex__<"div">;
  button?: Flex__<"button">;
  heroSection?: Flex__<"div">;
  container2?: Flex__<"div">;
  experienceTheFutureOfLuxuryLivingAcrossAfri?: Flex__<"div">;
  section?: Flex__<"div">;
  card?: Flex__<"div">;
  texts?: Flex__<"div">;
  contactPage2?: Flex__<"div">;
  subtext?: Flex__<"div">;
  contactPage3?: Flex__<"div">;
  contactPage4?: Flex__<"div">;
  card2?: Flex__<"div">;
  texts2?: Flex__<"div">;
  contactPage5?: Flex__<"div">;
  subtext2?: Flex__<"div">;
  contactPage6?: Flex__<"div">;
  contactPage7?: Flex__<"div">;
  sendUsMessage?: Flex__<"div">;
  card3?: Flex__<"div">;
  contactPage8?: Flex__<"div">;
  contactPage9?: Flex__<"div">;
  container3?: Flex__<"div">;
  container4?: Flex__<"div">;
  primitiveLabel?: Flex__<"div">;
  input?: Flex__<"div">;
  container5?: Flex__<"div">;
  primitiveLabel2?: Flex__<"div">;
  input2?: Flex__<"div">;
  container6?: Flex__<"div">;
  container7?: Flex__<"div">;
  primitiveLabel3?: Flex__<"div">;
  input3?: Flex__<"div">;
  container8?: Flex__<"div">;
  primitiveLabel4?: Flex__<"div">;
  primitiveButton?: Flex__<"div">;
  primitiveSpan?: Flex__<"div">;
  container9?: Flex__<"div">;
  primitiveLabel5?: Flex__<"div">;
  primitiveButton2?: Flex__<"div">;
  primitiveSpan2?: Flex__<"div">;
  container10?: Flex__<"div">;
  primitiveLabel6?: Flex__<"div">;
  textarea?: Flex__<"div">;
  button2?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  offices?: Flex__<"div">;
  container11?: Flex__<"div">;
  container12?: Flex__<"div">;
  experienceTheFutureOfLuxuryLivingAcrossAfri2?: Flex__<"div">;
  section2?: Flex__<"div">;
  card4?: Flex__<"div">;
  texts3?: Flex__<"div">;
  contactPage10?: Flex__<"div">;
  subtext3?: Flex__<"div">;
  contactPage11?: Flex__<"div">;
  contactPage12?: Flex__<"div">;
  contactPage13?: Flex__<"div">;
  button3?: Flex__<"div">;
  card5?: Flex__<"div">;
  texts4?: Flex__<"div">;
  contactPage14?: Flex__<"div">;
  subtext4?: Flex__<"div">;
  contactPage15?: Flex__<"div">;
  contactPage16?: Flex__<"div">;
  contactPage17?: Flex__<"div">;
  button4?: Flex__<"button">;
  card6?: Flex__<"div">;
  texts5?: Flex__<"div">;
  contactPage18?: Flex__<"div">;
  subtext5?: Flex__<"div">;
  contactPage19?: Flex__<"div">;
  contactPage20?: Flex__<"div">;
  contactPage21?: Flex__<"div">;
  button5?: Flex__<"button">;
  footer?: Flex__<"div">;
  container13?: Flex__<"div">;
  left?: Flex__<"div">;
  logo2?: Flex__<"div">;
  logo3?: Flex__<"div">;
  logoMark2?: Flex__<"div">;
  texts6?: Flex__<"div">;
  paragraph?: Flex__<"div">;
  paragraph2?: Flex__<"div">;
  right?: Flex__<"div">;
  container14?: Flex__<"div">;
  header2?: Flex__<"div">;
  list?: Flex__<"div">;
  listItem?: Flex__<"div">;
  link6?: Flex__<"div">;
  listItem2?: Flex__<"div">;
  link7?: Flex__<"div">;
  listItem3?: Flex__<"div">;
  link8?: Flex__<"div">;
  listItem4?: Flex__<"div">;
  link9?: Flex__<"div">;
  container15?: Flex__<"div">;
  header3?: Flex__<"div">;
  list2?: Flex__<"div">;
  listItem5?: Flex__<"div">;
  listItem6?: Flex__<"div">;
  container16?: Flex__<"div">;
  link10?: Flex__<"div">;
  link11?: Flex__<"div">;
  link12?: Flex__<"div">;
  container17?: Flex__<"div">;
  container18?: Flex__<"div">;
  paragraph3?: Flex__<"div">;
  _2025HouseNo5ByAfriNestAllRightsReserve?: Flex__<"div">;
  container19?: Flex__<"div">;
  text?: Flex__<"div">;
  link13?: Flex__<"div">;
  link14?: Flex__<"div">;
  link15?: Flex__<"div">;
};

export interface DefaultContactProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicContact__RenderFunc(props: {
  variants: PlasmicContact__VariantsArgs;
  args: PlasmicContact__ArgsType;
  overrides: PlasmicContact__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"contactPage"}
            data-plasmic-override={overrides.contactPage}
            className={classNames(projectcss.all, sty.contactPage)}
          >
            <div
              data-plasmic-name={"headerHeroSection"}
              data-plasmic-override={overrides.headerHeroSection}
              className={classNames(projectcss.all, sty.headerHeroSection)}
            >
              <div
                data-plasmic-name={"header"}
                data-plasmic-override={overrides.header}
                className={classNames(projectcss.all, sty.header)}
              >
                <div
                  data-plasmic-name={"container"}
                  data-plasmic-override={overrides.container}
                  className={classNames(projectcss.all, sty.container)}
                >
                  <div
                    data-plasmic-name={"logo"}
                    data-plasmic-override={overrides.logo}
                    className={classNames(projectcss.all, sty.logo)}
                  >
                    <div
                      data-plasmic-name={"logoMark"}
                      data-plasmic-override={overrides.logoMark}
                      className={classNames(projectcss.all, sty.logoMark)}
                    >
                      <VectorIcon
                        className={classNames(projectcss.all, sty.svg__mZ7Fi)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___7Inr
                        )}
                      >
                        {"5"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lWci6
                      )}
                    >
                      {"HOUSE NO. 5"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"navigationMenu"}
                    data-plasmic-override={overrides.navigationMenu}
                    className={classNames(projectcss.all, sty.navigationMenu)}
                  >
                    <div
                      data-plasmic-name={"link"}
                      data-plasmic-override={overrides.link}
                      className={classNames(projectcss.all, sty.link)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__g6BoS
                        )}
                        component={Link}
                        href={`/`}
                        platform={"nextjs"}
                      >
                        {"Home"}
                      </PlasmicLink__>
                    </div>
                    <div
                      data-plasmic-name={"link2"}
                      data-plasmic-override={overrides.link2}
                      className={classNames(projectcss.all, sty.link2)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__xhMlu
                        )}
                        component={Link}
                        href={`/our-developments`}
                        platform={"nextjs"}
                      >
                        {"Our Developments"}
                      </PlasmicLink__>
                    </div>
                    <div
                      data-plasmic-name={"link3"}
                      data-plasmic-override={overrides.link3}
                      className={classNames(projectcss.all, sty.link3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__loAaq
                        )}
                      >
                        {"About"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"link4"}
                      data-plasmic-override={overrides.link4}
                      className={classNames(projectcss.all, sty.link4)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uX7Ld
                        )}
                      >
                        {"Smart Living"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"link5"}
                      data-plasmic-override={overrides.link5}
                      className={classNames(projectcss.all, sty.link5)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__ytvc
                        )}
                        component={Link}
                        href={`/contact`}
                        platform={"nextjs"}
                      >
                        {"Contact"}
                      </PlasmicLink__>
                    </div>
                  </div>
                  <button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      sty.button
                    )}
                    ref={ref => {
                      $refs["button"] = ref;
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kmKog
                      )}
                    >
                      {"Log in"}
                    </div>
                  </button>
                </div>
              </div>
              <div
                data-plasmic-name={"heroSection"}
                data-plasmic-override={overrides.heroSection}
                className={classNames(projectcss.all, sty.heroSection)}
              >
                <div
                  data-plasmic-name={"container2"}
                  data-plasmic-override={overrides.container2}
                  className={classNames(projectcss.all, sty.container2)}
                >
                  <div
                    data-plasmic-name={
                      "experienceTheFutureOfLuxuryLivingAcrossAfri"
                    }
                    data-plasmic-override={
                      overrides.experienceTheFutureOfLuxuryLivingAcrossAfri
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.experienceTheFutureOfLuxuryLivingAcrossAfri
                    )}
                  >
                    {"Get in Touch"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cpnhJ
                    )}
                  >
                    {
                      "Have questions about our properties? Our team is here to help you find your dream home."
                    }
                  </div>
                </div>
                <div
                  data-plasmic-name={"section"}
                  data-plasmic-override={overrides.section}
                  className={classNames(projectcss.all, sty.section)}
                >
                  <div
                    data-plasmic-name={"card"}
                    data-plasmic-override={overrides.card}
                    className={classNames(projectcss.all, sty.card)}
                  >
                    <Icon9Icon
                      className={classNames(projectcss.all, sty.svg__mZl4V)}
                      role={"img"}
                    />

                    <div
                      data-plasmic-name={"texts"}
                      data-plasmic-override={overrides.texts}
                      className={classNames(projectcss.all, sty.texts)}
                    >
                      <div
                        data-plasmic-name={"contactPage2"}
                        data-plasmic-override={overrides.contactPage2}
                        className={classNames(projectcss.all, sty.contactPage2)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__g6Mfr
                          )}
                        >
                          {"Phone"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"subtext"}
                        data-plasmic-override={overrides.subtext}
                        className={classNames(projectcss.all, sty.subtext)}
                      >
                        <div
                          data-plasmic-name={"contactPage3"}
                          data-plasmic-override={overrides.contactPage3}
                          className={classNames(
                            projectcss.all,
                            sty.contactPage3
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__tbH5M
                            )}
                          >
                            {"Mon-Fri 8am to 6pm EAT"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"contactPage4"}
                          data-plasmic-override={overrides.contactPage4}
                          className={classNames(
                            projectcss.all,
                            sty.contactPage4
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___7Ku3T
                            )}
                          >
                            {"+1 (555) 123-4567"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"card2"}
                    data-plasmic-override={overrides.card2}
                    className={classNames(projectcss.all, sty.card2)}
                  >
                    <Icon10Icon
                      className={classNames(projectcss.all, sty.svg___080Jc)}
                      role={"img"}
                    />

                    <div
                      data-plasmic-name={"texts2"}
                      data-plasmic-override={overrides.texts2}
                      className={classNames(projectcss.all, sty.texts2)}
                    >
                      <div
                        data-plasmic-name={"contactPage5"}
                        data-plasmic-override={overrides.contactPage5}
                        className={classNames(projectcss.all, sty.contactPage5)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___4Bz8Y
                          )}
                        >
                          {"Email"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"subtext2"}
                        data-plasmic-override={overrides.subtext2}
                        className={classNames(projectcss.all, sty.subtext2)}
                      >
                        <div
                          data-plasmic-name={"contactPage6"}
                          data-plasmic-override={overrides.contactPage6}
                          className={classNames(
                            projectcss.all,
                            sty.contactPage6
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__lNhmf
                            )}
                          >
                            {"We'll respond within 24 hours"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"contactPage7"}
                          data-plasmic-override={overrides.contactPage7}
                          className={classNames(
                            projectcss.all,
                            sty.contactPage7
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__bvc9N
                            )}
                          >
                            {"info@houseno5.com"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"sendUsMessage"}
              data-plasmic-override={overrides.sendUsMessage}
              className={classNames(projectcss.all, sty.sendUsMessage)}
            >
              <div
                data-plasmic-name={"card3"}
                data-plasmic-override={overrides.card3}
                className={classNames(projectcss.all, sty.card3)}
              >
                <div
                  data-plasmic-name={"contactPage8"}
                  data-plasmic-override={overrides.contactPage8}
                  className={classNames(projectcss.all, sty.contactPage8)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4P7Vw
                    )}
                  >
                    {"Send us a Message"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"contactPage9"}
                  data-plasmic-override={overrides.contactPage9}
                  className={classNames(projectcss.all, sty.contactPage9)}
                >
                  <div
                    data-plasmic-name={"container3"}
                    data-plasmic-override={overrides.container3}
                    className={classNames(projectcss.all, sty.container3)}
                  >
                    <div
                      data-plasmic-name={"container4"}
                      data-plasmic-override={overrides.container4}
                      className={classNames(projectcss.all, sty.container4)}
                    >
                      <div
                        data-plasmic-name={"primitiveLabel"}
                        data-plasmic-override={overrides.primitiveLabel}
                        className={classNames(
                          projectcss.all,
                          sty.primitiveLabel
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kFcG8
                          )}
                        >
                          {"Full Name *"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"input"}
                        data-plasmic-override={overrides.input}
                        className={classNames(projectcss.all, sty.input)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__y5Lwm
                          )}
                        >
                          {"John Doe"}
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"container5"}
                      data-plasmic-override={overrides.container5}
                      className={classNames(projectcss.all, sty.container5)}
                    >
                      <div
                        data-plasmic-name={"primitiveLabel2"}
                        data-plasmic-override={overrides.primitiveLabel2}
                        className={classNames(
                          projectcss.all,
                          sty.primitiveLabel2
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zxs8
                          )}
                        >
                          {"Email Address *"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"input2"}
                        data-plasmic-override={overrides.input2}
                        className={classNames(projectcss.all, sty.input2)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vsUsy
                          )}
                        >
                          {"john@example.com"}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"container6"}
                    data-plasmic-override={overrides.container6}
                    className={classNames(projectcss.all, sty.container6)}
                  >
                    <div
                      data-plasmic-name={"container7"}
                      data-plasmic-override={overrides.container7}
                      className={classNames(projectcss.all, sty.container7)}
                    >
                      <div
                        data-plasmic-name={"primitiveLabel3"}
                        data-plasmic-override={overrides.primitiveLabel3}
                        className={classNames(
                          projectcss.all,
                          sty.primitiveLabel3
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kYvGg
                          )}
                        >
                          {"Phone Number"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"input3"}
                        data-plasmic-override={overrides.input3}
                        className={classNames(projectcss.all, sty.input3)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__bumO8
                          )}
                        >
                          {"+1 234 567 8900"}
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"container8"}
                      data-plasmic-override={overrides.container8}
                      className={classNames(projectcss.all, sty.container8)}
                    >
                      <div
                        data-plasmic-name={"primitiveLabel4"}
                        data-plasmic-override={overrides.primitiveLabel4}
                        className={classNames(
                          projectcss.all,
                          sty.primitiveLabel4
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___2Vso
                          )}
                        >
                          {"Country *"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"primitiveButton"}
                        data-plasmic-override={overrides.primitiveButton}
                        className={classNames(
                          projectcss.all,
                          sty.primitiveButton
                        )}
                      >
                        <div
                          data-plasmic-name={"primitiveSpan"}
                          data-plasmic-override={overrides.primitiveSpan}
                          className={classNames(
                            projectcss.all,
                            sty.primitiveSpan
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__lqeLx
                            )}
                          >
                            {"Select a country"}
                          </div>
                        </div>
                        <Icon11Icon
                          className={classNames(projectcss.all, sty.svg__gUysq)}
                          role={"img"}
                        />
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"container9"}
                    data-plasmic-override={overrides.container9}
                    className={classNames(projectcss.all, sty.container9)}
                  >
                    <div
                      data-plasmic-name={"primitiveLabel5"}
                      data-plasmic-override={overrides.primitiveLabel5}
                      className={classNames(
                        projectcss.all,
                        sty.primitiveLabel5
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__y0ZMd
                        )}
                      >
                        {"Subject *"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"primitiveButton2"}
                      data-plasmic-override={overrides.primitiveButton2}
                      className={classNames(
                        projectcss.all,
                        sty.primitiveButton2
                      )}
                    >
                      <div
                        data-plasmic-name={"primitiveSpan2"}
                        data-plasmic-override={overrides.primitiveSpan2}
                        className={classNames(
                          projectcss.all,
                          sty.primitiveSpan2
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fXqOa
                          )}
                        >
                          {"What can we help you with?"}
                        </div>
                      </div>
                      <Icon11Icon
                        className={classNames(projectcss.all, sty.svg__pmJgK)}
                        role={"img"}
                      />
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"container10"}
                    data-plasmic-override={overrides.container10}
                    className={classNames(projectcss.all, sty.container10)}
                  >
                    <div
                      data-plasmic-name={"primitiveLabel6"}
                      data-plasmic-override={overrides.primitiveLabel6}
                      className={classNames(
                        projectcss.all,
                        sty.primitiveLabel6
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fRtYv
                        )}
                      >
                        {"Message *"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"textarea"}
                      data-plasmic-override={overrides.textarea}
                      className={classNames(projectcss.all, sty.textarea)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uuhGr
                        )}
                      >
                        {"Tell us about your requirements..."}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"button2"}
                    data-plasmic-override={overrides.button2}
                    className={classNames(projectcss.all, sty.button2)}
                  >
                    <PlasmicImg__
                      data-plasmic-name={"img"}
                      data-plasmic-override={overrides.img}
                      alt={""}
                      className={classNames(sty.img)}
                      displayHeight={"16px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"16px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/website_starter/images/icon12.svg",
                        fullWidth: 16,
                        fullHeight: 16,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ekZkn
                      )}
                    >
                      {"Send a Message"}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"offices"}
              data-plasmic-override={overrides.offices}
              className={classNames(projectcss.all, sty.offices)}
            >
              <div
                data-plasmic-name={"container11"}
                data-plasmic-override={overrides.container11}
                className={classNames(projectcss.all, sty.container11)}
              >
                <div
                  data-plasmic-name={"container12"}
                  data-plasmic-override={overrides.container12}
                  className={classNames(projectcss.all, sty.container12)}
                >
                  <div
                    data-plasmic-name={
                      "experienceTheFutureOfLuxuryLivingAcrossAfri2"
                    }
                    data-plasmic-override={
                      overrides.experienceTheFutureOfLuxuryLivingAcrossAfri2
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.experienceTheFutureOfLuxuryLivingAcrossAfri2
                    )}
                  >
                    {"Our Offices"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6ZgbH
                    )}
                  >
                    {"Visit us ar any of our locations across Africa"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"section2"}
                  data-plasmic-override={overrides.section2}
                  className={classNames(projectcss.all, sty.section2)}
                >
                  <div
                    data-plasmic-name={"card4"}
                    data-plasmic-override={overrides.card4}
                    className={classNames(projectcss.all, sty.card4)}
                  >
                    <Icon13Icon
                      className={classNames(projectcss.all, sty.svg__kr24Q)}
                      role={"img"}
                    />

                    <div
                      data-plasmic-name={"texts3"}
                      data-plasmic-override={overrides.texts3}
                      className={classNames(projectcss.all, sty.texts3)}
                    >
                      <div
                        data-plasmic-name={"contactPage10"}
                        data-plasmic-override={overrides.contactPage10}
                        className={classNames(
                          projectcss.all,
                          sty.contactPage10
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__oTfIt
                          )}
                        >
                          {"Nairobi, Kenya"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"subtext3"}
                        data-plasmic-override={overrides.subtext3}
                        className={classNames(projectcss.all, sty.subtext3)}
                      >
                        <div
                          data-plasmic-name={"contactPage11"}
                          data-plasmic-override={overrides.contactPage11}
                          className={classNames(
                            projectcss.all,
                            sty.contactPage11
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__iybs
                            )}
                          >
                            {"123 Walyaki Way, Westlands"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"contactPage12"}
                          data-plasmic-override={overrides.contactPage12}
                          className={classNames(
                            projectcss.all,
                            sty.contactPage12
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__q2BFv
                            )}
                          >
                            {"+1 (555) 123-4567"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"contactPage13"}
                          data-plasmic-override={overrides.contactPage13}
                          className={classNames(
                            projectcss.all,
                            sty.contactPage13
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__nuAg2
                            )}
                          >
                            {"nairobi@houseno5.com"}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"button3"}
                      data-plasmic-override={overrides.button3}
                      className={classNames(projectcss.all, sty.button3)}
                    >
                      <button
                        className={classNames(
                          projectcss.all,
                          projectcss.button,
                          projectcss.__wab_text,
                          sty.button__cCwqy
                        )}
                      >
                        {"Get Directions"}
                      </button>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"card5"}
                    data-plasmic-override={overrides.card5}
                    className={classNames(projectcss.all, sty.card5)}
                  >
                    <Icon13Icon
                      className={classNames(projectcss.all, sty.svg__o2BBq)}
                      role={"img"}
                    />

                    <div
                      data-plasmic-name={"texts4"}
                      data-plasmic-override={overrides.texts4}
                      className={classNames(projectcss.all, sty.texts4)}
                    >
                      <div
                        data-plasmic-name={"contactPage14"}
                        data-plasmic-override={overrides.contactPage14}
                        className={classNames(
                          projectcss.all,
                          sty.contactPage14
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___1Nl0Q
                          )}
                        >
                          {"CapeTown, South Africa"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"subtext4"}
                        data-plasmic-override={overrides.subtext4}
                        className={classNames(projectcss.all, sty.subtext4)}
                      >
                        <div
                          data-plasmic-name={"contactPage15"}
                          data-plasmic-override={overrides.contactPage15}
                          className={classNames(
                            projectcss.all,
                            sty.contactPage15
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___3YJnz
                            )}
                          >
                            {"456 Victoria\u2019s road, Camps Bay"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"contactPage16"}
                          data-plasmic-override={overrides.contactPage16}
                          className={classNames(
                            projectcss.all,
                            sty.contactPage16
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__kGpRw
                            )}
                          >
                            {"+27 21 123 4567"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"contactPage17"}
                          data-plasmic-override={overrides.contactPage17}
                          className={classNames(
                            projectcss.all,
                            sty.contactPage17
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xp8Qy
                            )}
                          >
                            {"capetown@houseno5.com"}
                          </div>
                        </div>
                      </div>
                    </div>
                    <button
                      data-plasmic-name={"button4"}
                      data-plasmic-override={overrides.button4}
                      className={classNames(
                        projectcss.all,
                        projectcss.button,
                        sty.button4
                      )}
                      ref={ref => {
                        $refs["button4"] = ref;
                      }}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__i6Xyj
                        )}
                      >
                        {"Get Directions"}
                      </div>
                    </button>
                  </div>
                  <div
                    data-plasmic-name={"card6"}
                    data-plasmic-override={overrides.card6}
                    className={classNames(projectcss.all, sty.card6)}
                  >
                    <Icon13Icon
                      className={classNames(projectcss.all, sty.svg__xe7OF)}
                      role={"img"}
                    />

                    <div
                      data-plasmic-name={"texts5"}
                      data-plasmic-override={overrides.texts5}
                      className={classNames(projectcss.all, sty.texts5)}
                    >
                      <div
                        data-plasmic-name={"contactPage18"}
                        data-plasmic-override={overrides.contactPage18}
                        className={classNames(
                          projectcss.all,
                          sty.contactPage18
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__v2TEk
                          )}
                        >
                          {"Lagos, Nigeria"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"subtext5"}
                        data-plasmic-override={overrides.subtext5}
                        className={classNames(projectcss.all, sty.subtext5)}
                      >
                        <div
                          data-plasmic-name={"contactPage19"}
                          data-plasmic-override={overrides.contactPage19}
                          className={classNames(
                            projectcss.all,
                            sty.contactPage19
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ldHlW
                            )}
                          >
                            {"786 Victoria Island, Lagos"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"contactPage20"}
                          data-plasmic-override={overrides.contactPage20}
                          className={classNames(
                            projectcss.all,
                            sty.contactPage20
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rmGo3
                            )}
                          >
                            {"+234 21 123 4567"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"contactPage21"}
                          data-plasmic-override={overrides.contactPage21}
                          className={classNames(
                            projectcss.all,
                            sty.contactPage21
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__tMdVn
                            )}
                          >
                            {"lagos@houseno5.com"}
                          </div>
                        </div>
                      </div>
                    </div>
                    <button
                      data-plasmic-name={"button5"}
                      data-plasmic-override={overrides.button5}
                      className={classNames(
                        projectcss.all,
                        projectcss.button,
                        sty.button5
                      )}
                      ref={ref => {
                        $refs["button5"] = ref;
                      }}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kVtS4
                        )}
                      >
                        {"Get Directions"}
                      </div>
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(projectcss.all, sty.footer)}
            >
              <div
                data-plasmic-name={"container13"}
                data-plasmic-override={overrides.container13}
                className={classNames(projectcss.all, sty.container13)}
              >
                <div
                  data-plasmic-name={"left"}
                  data-plasmic-override={overrides.left}
                  className={classNames(projectcss.all, sty.left)}
                >
                  <div
                    data-plasmic-name={"logo2"}
                    data-plasmic-override={overrides.logo2}
                    className={classNames(projectcss.all, sty.logo2)}
                  >
                    <div
                      data-plasmic-name={"logo3"}
                      data-plasmic-override={overrides.logo3}
                      className={classNames(projectcss.all, sty.logo3)}
                    >
                      <div
                        data-plasmic-name={"logoMark2"}
                        data-plasmic-override={overrides.logoMark2}
                        className={classNames(projectcss.all, sty.logoMark2)}
                      >
                        <Vector3Icon
                          className={classNames(projectcss.all, sty.svg__yKk4J)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kEt0
                          )}
                        >
                          {"5"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mKt02
                        )}
                      >
                        {"HOUSE NO. 5"}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"texts6"}
                    data-plasmic-override={overrides.texts6}
                    className={classNames(projectcss.all, sty.texts6)}
                  >
                    <div
                      data-plasmic-name={"paragraph"}
                      data-plasmic-override={overrides.paragraph}
                      className={classNames(projectcss.all, sty.paragraph)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bEj3N
                        )}
                      >
                        {"Elegant. Sustainable. African."}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"paragraph2"}
                      data-plasmic-override={overrides.paragraph2}
                      className={classNames(projectcss.all, sty.paragraph2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__amm92
                        )}
                      >
                        {"Premium smart city developments across Africa."}
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"right"}
                  data-plasmic-override={overrides.right}
                  className={classNames(projectcss.all, sty.right)}
                >
                  <div
                    data-plasmic-name={"container14"}
                    data-plasmic-override={overrides.container14}
                    className={classNames(projectcss.all, sty.container14)}
                  >
                    <div
                      data-plasmic-name={"header2"}
                      data-plasmic-override={overrides.header2}
                      className={classNames(projectcss.all, sty.header2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___14Hv0
                        )}
                      >
                        {"Quick Links"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"list"}
                      data-plasmic-override={overrides.list}
                      className={classNames(projectcss.all, sty.list)}
                    >
                      <div
                        data-plasmic-name={"listItem"}
                        data-plasmic-override={overrides.listItem}
                        className={classNames(projectcss.all, sty.listItem)}
                      >
                        <div
                          data-plasmic-name={"link6"}
                          data-plasmic-override={overrides.link6}
                          className={classNames(projectcss.all, sty.link6)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___6TdF
                            )}
                          >
                            {"Browse Estates"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"listItem2"}
                        data-plasmic-override={overrides.listItem2}
                        className={classNames(projectcss.all, sty.listItem2)}
                      >
                        <div
                          data-plasmic-name={"link7"}
                          data-plasmic-override={overrides.link7}
                          className={classNames(projectcss.all, sty.link7)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___6Egza
                            )}
                          >
                            {"About Us"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"listItem3"}
                        data-plasmic-override={overrides.listItem3}
                        className={classNames(projectcss.all, sty.listItem3)}
                      >
                        <div
                          data-plasmic-name={"link8"}
                          data-plasmic-override={overrides.link8}
                          className={classNames(projectcss.all, sty.link8)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wk35V
                            )}
                          >
                            {"Smart Living"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"listItem4"}
                        data-plasmic-override={overrides.listItem4}
                        className={classNames(projectcss.all, sty.listItem4)}
                      >
                        <div
                          data-plasmic-name={"link9"}
                          data-plasmic-override={overrides.link9}
                          className={classNames(projectcss.all, sty.link9)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__mmrA5
                            )}
                          >
                            {"Contact"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"container15"}
                    data-plasmic-override={overrides.container15}
                    className={classNames(projectcss.all, sty.container15)}
                  >
                    <div
                      data-plasmic-name={"header3"}
                      data-plasmic-override={overrides.header3}
                      className={classNames(projectcss.all, sty.header3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__di3V1
                        )}
                      >
                        {"Connect"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"list2"}
                      data-plasmic-override={overrides.list2}
                      className={classNames(projectcss.all, sty.list2)}
                    >
                      <div
                        data-plasmic-name={"listItem5"}
                        data-plasmic-override={overrides.listItem5}
                        className={classNames(projectcss.all, sty.listItem5)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zVLw
                          )}
                        >
                          {"info@houseno5.com"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"listItem6"}
                        data-plasmic-override={overrides.listItem6}
                        className={classNames(projectcss.all, sty.listItem6)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__njP2
                          )}
                        >
                          {"+1 (555) 123-4567"}
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"container16"}
                      data-plasmic-override={overrides.container16}
                      className={classNames(projectcss.all, sty.container16)}
                    >
                      <div
                        data-plasmic-name={"link10"}
                        data-plasmic-override={overrides.link10}
                        className={classNames(projectcss.all, sty.link10)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qoSgS
                          )}
                        >
                          {"LinkedIn"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"link11"}
                        data-plasmic-override={overrides.link11}
                        className={classNames(projectcss.all, sty.link11)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zhzPu
                          )}
                        >
                          {"Instagram"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"link12"}
                        data-plasmic-override={overrides.link12}
                        className={classNames(projectcss.all, sty.link12)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__i0BFq
                          )}
                        >
                          {"Twitter"}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"container17"}
                data-plasmic-override={overrides.container17}
                className={classNames(projectcss.all, sty.container17)}
              >
                <div
                  data-plasmic-name={"container18"}
                  data-plasmic-override={overrides.container18}
                  className={classNames(projectcss.all, sty.container18)}
                >
                  <div
                    data-plasmic-name={"paragraph3"}
                    data-plasmic-override={overrides.paragraph3}
                    className={classNames(projectcss.all, sty.paragraph3)}
                  >
                    <div
                      data-plasmic-name={
                        "_2025HouseNo5ByAfriNestAllRightsReserve"
                      }
                      data-plasmic-override={
                        overrides._2025HouseNo5ByAfriNestAllRightsReserve
                      }
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty._2025HouseNo5ByAfriNestAllRightsReserve
                      )}
                    >
                      {
                        "\u00a9 2025 House No. 5 by AfriNest. All rights reserved."
                      }
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"container19"}
                    data-plasmic-override={overrides.container19}
                    className={classNames(projectcss.all, sty.container19)}
                  >
                    <div
                      data-plasmic-name={"text"}
                      data-plasmic-override={overrides.text}
                      className={classNames(projectcss.all, sty.text)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__otttv
                        )}
                      >
                        {"Sister Brands:"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"link13"}
                      data-plasmic-override={overrides.link13}
                      className={classNames(projectcss.all, sty.link13)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jqNrA
                        )}
                      >
                        {"AfriNest"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"link14"}
                      data-plasmic-override={overrides.link14}
                      className={classNames(projectcss.all, sty.link14)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__puWve
                        )}
                      >
                        {"Urban Edge"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"link15"}
                      data-plasmic-override={overrides.link15}
                      className={classNames(projectcss.all, sty.link15)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qnVa1
                        )}
                      >
                        {"Green Haven"}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "contactPage",
    "headerHeroSection",
    "header",
    "container",
    "logo",
    "logoMark",
    "navigationMenu",
    "link",
    "link2",
    "link3",
    "link4",
    "link5",
    "button",
    "heroSection",
    "container2",
    "experienceTheFutureOfLuxuryLivingAcrossAfri",
    "section",
    "card",
    "texts",
    "contactPage2",
    "subtext",
    "contactPage3",
    "contactPage4",
    "card2",
    "texts2",
    "contactPage5",
    "subtext2",
    "contactPage6",
    "contactPage7",
    "sendUsMessage",
    "card3",
    "contactPage8",
    "contactPage9",
    "container3",
    "container4",
    "primitiveLabel",
    "input",
    "container5",
    "primitiveLabel2",
    "input2",
    "container6",
    "container7",
    "primitiveLabel3",
    "input3",
    "container8",
    "primitiveLabel4",
    "primitiveButton",
    "primitiveSpan",
    "container9",
    "primitiveLabel5",
    "primitiveButton2",
    "primitiveSpan2",
    "container10",
    "primitiveLabel6",
    "textarea",
    "button2",
    "img",
    "offices",
    "container11",
    "container12",
    "experienceTheFutureOfLuxuryLivingAcrossAfri2",
    "section2",
    "card4",
    "texts3",
    "contactPage10",
    "subtext3",
    "contactPage11",
    "contactPage12",
    "contactPage13",
    "button3",
    "card5",
    "texts4",
    "contactPage14",
    "subtext4",
    "contactPage15",
    "contactPage16",
    "contactPage17",
    "button4",
    "card6",
    "texts5",
    "contactPage18",
    "subtext5",
    "contactPage19",
    "contactPage20",
    "contactPage21",
    "button5",
    "footer",
    "container13",
    "left",
    "logo2",
    "logo3",
    "logoMark2",
    "texts6",
    "paragraph",
    "paragraph2",
    "right",
    "container14",
    "header2",
    "list",
    "listItem",
    "link6",
    "listItem2",
    "link7",
    "listItem3",
    "link8",
    "listItem4",
    "link9",
    "container15",
    "header3",
    "list2",
    "listItem5",
    "listItem6",
    "container16",
    "link10",
    "link11",
    "link12",
    "container17",
    "container18",
    "paragraph3",
    "_2025HouseNo5ByAfriNestAllRightsReserve",
    "container19",
    "text",
    "link13",
    "link14",
    "link15"
  ],
  contactPage: [
    "contactPage",
    "headerHeroSection",
    "header",
    "container",
    "logo",
    "logoMark",
    "navigationMenu",
    "link",
    "link2",
    "link3",
    "link4",
    "link5",
    "button",
    "heroSection",
    "container2",
    "experienceTheFutureOfLuxuryLivingAcrossAfri",
    "section",
    "card",
    "texts",
    "contactPage2",
    "subtext",
    "contactPage3",
    "contactPage4",
    "card2",
    "texts2",
    "contactPage5",
    "subtext2",
    "contactPage6",
    "contactPage7",
    "sendUsMessage",
    "card3",
    "contactPage8",
    "contactPage9",
    "container3",
    "container4",
    "primitiveLabel",
    "input",
    "container5",
    "primitiveLabel2",
    "input2",
    "container6",
    "container7",
    "primitiveLabel3",
    "input3",
    "container8",
    "primitiveLabel4",
    "primitiveButton",
    "primitiveSpan",
    "container9",
    "primitiveLabel5",
    "primitiveButton2",
    "primitiveSpan2",
    "container10",
    "primitiveLabel6",
    "textarea",
    "button2",
    "img",
    "offices",
    "container11",
    "container12",
    "experienceTheFutureOfLuxuryLivingAcrossAfri2",
    "section2",
    "card4",
    "texts3",
    "contactPage10",
    "subtext3",
    "contactPage11",
    "contactPage12",
    "contactPage13",
    "button3",
    "card5",
    "texts4",
    "contactPage14",
    "subtext4",
    "contactPage15",
    "contactPage16",
    "contactPage17",
    "button4",
    "card6",
    "texts5",
    "contactPage18",
    "subtext5",
    "contactPage19",
    "contactPage20",
    "contactPage21",
    "button5",
    "footer",
    "container13",
    "left",
    "logo2",
    "logo3",
    "logoMark2",
    "texts6",
    "paragraph",
    "paragraph2",
    "right",
    "container14",
    "header2",
    "list",
    "listItem",
    "link6",
    "listItem2",
    "link7",
    "listItem3",
    "link8",
    "listItem4",
    "link9",
    "container15",
    "header3",
    "list2",
    "listItem5",
    "listItem6",
    "container16",
    "link10",
    "link11",
    "link12",
    "container17",
    "container18",
    "paragraph3",
    "_2025HouseNo5ByAfriNestAllRightsReserve",
    "container19",
    "text",
    "link13",
    "link14",
    "link15"
  ],
  headerHeroSection: [
    "headerHeroSection",
    "header",
    "container",
    "logo",
    "logoMark",
    "navigationMenu",
    "link",
    "link2",
    "link3",
    "link4",
    "link5",
    "button",
    "heroSection",
    "container2",
    "experienceTheFutureOfLuxuryLivingAcrossAfri",
    "section",
    "card",
    "texts",
    "contactPage2",
    "subtext",
    "contactPage3",
    "contactPage4",
    "card2",
    "texts2",
    "contactPage5",
    "subtext2",
    "contactPage6",
    "contactPage7"
  ],
  header: [
    "header",
    "container",
    "logo",
    "logoMark",
    "navigationMenu",
    "link",
    "link2",
    "link3",
    "link4",
    "link5",
    "button"
  ],
  container: [
    "container",
    "logo",
    "logoMark",
    "navigationMenu",
    "link",
    "link2",
    "link3",
    "link4",
    "link5",
    "button"
  ],
  logo: ["logo", "logoMark"],
  logoMark: ["logoMark"],
  navigationMenu: [
    "navigationMenu",
    "link",
    "link2",
    "link3",
    "link4",
    "link5"
  ],
  link: ["link"],
  link2: ["link2"],
  link3: ["link3"],
  link4: ["link4"],
  link5: ["link5"],
  button: ["button"],
  heroSection: [
    "heroSection",
    "container2",
    "experienceTheFutureOfLuxuryLivingAcrossAfri",
    "section",
    "card",
    "texts",
    "contactPage2",
    "subtext",
    "contactPage3",
    "contactPage4",
    "card2",
    "texts2",
    "contactPage5",
    "subtext2",
    "contactPage6",
    "contactPage7"
  ],
  container2: ["container2", "experienceTheFutureOfLuxuryLivingAcrossAfri"],
  experienceTheFutureOfLuxuryLivingAcrossAfri: [
    "experienceTheFutureOfLuxuryLivingAcrossAfri"
  ],
  section: [
    "section",
    "card",
    "texts",
    "contactPage2",
    "subtext",
    "contactPage3",
    "contactPage4",
    "card2",
    "texts2",
    "contactPage5",
    "subtext2",
    "contactPage6",
    "contactPage7"
  ],
  card: [
    "card",
    "texts",
    "contactPage2",
    "subtext",
    "contactPage3",
    "contactPage4"
  ],
  texts: ["texts", "contactPage2", "subtext", "contactPage3", "contactPage4"],
  contactPage2: ["contactPage2"],
  subtext: ["subtext", "contactPage3", "contactPage4"],
  contactPage3: ["contactPage3"],
  contactPage4: ["contactPage4"],
  card2: [
    "card2",
    "texts2",
    "contactPage5",
    "subtext2",
    "contactPage6",
    "contactPage7"
  ],
  texts2: [
    "texts2",
    "contactPage5",
    "subtext2",
    "contactPage6",
    "contactPage7"
  ],
  contactPage5: ["contactPage5"],
  subtext2: ["subtext2", "contactPage6", "contactPage7"],
  contactPage6: ["contactPage6"],
  contactPage7: ["contactPage7"],
  sendUsMessage: [
    "sendUsMessage",
    "card3",
    "contactPage8",
    "contactPage9",
    "container3",
    "container4",
    "primitiveLabel",
    "input",
    "container5",
    "primitiveLabel2",
    "input2",
    "container6",
    "container7",
    "primitiveLabel3",
    "input3",
    "container8",
    "primitiveLabel4",
    "primitiveButton",
    "primitiveSpan",
    "container9",
    "primitiveLabel5",
    "primitiveButton2",
    "primitiveSpan2",
    "container10",
    "primitiveLabel6",
    "textarea",
    "button2",
    "img"
  ],
  card3: [
    "card3",
    "contactPage8",
    "contactPage9",
    "container3",
    "container4",
    "primitiveLabel",
    "input",
    "container5",
    "primitiveLabel2",
    "input2",
    "container6",
    "container7",
    "primitiveLabel3",
    "input3",
    "container8",
    "primitiveLabel4",
    "primitiveButton",
    "primitiveSpan",
    "container9",
    "primitiveLabel5",
    "primitiveButton2",
    "primitiveSpan2",
    "container10",
    "primitiveLabel6",
    "textarea",
    "button2",
    "img"
  ],
  contactPage8: ["contactPage8"],
  contactPage9: [
    "contactPage9",
    "container3",
    "container4",
    "primitiveLabel",
    "input",
    "container5",
    "primitiveLabel2",
    "input2",
    "container6",
    "container7",
    "primitiveLabel3",
    "input3",
    "container8",
    "primitiveLabel4",
    "primitiveButton",
    "primitiveSpan",
    "container9",
    "primitiveLabel5",
    "primitiveButton2",
    "primitiveSpan2",
    "container10",
    "primitiveLabel6",
    "textarea",
    "button2",
    "img"
  ],
  container3: [
    "container3",
    "container4",
    "primitiveLabel",
    "input",
    "container5",
    "primitiveLabel2",
    "input2"
  ],
  container4: ["container4", "primitiveLabel", "input"],
  primitiveLabel: ["primitiveLabel"],
  input: ["input"],
  container5: ["container5", "primitiveLabel2", "input2"],
  primitiveLabel2: ["primitiveLabel2"],
  input2: ["input2"],
  container6: [
    "container6",
    "container7",
    "primitiveLabel3",
    "input3",
    "container8",
    "primitiveLabel4",
    "primitiveButton",
    "primitiveSpan"
  ],
  container7: ["container7", "primitiveLabel3", "input3"],
  primitiveLabel3: ["primitiveLabel3"],
  input3: ["input3"],
  container8: [
    "container8",
    "primitiveLabel4",
    "primitiveButton",
    "primitiveSpan"
  ],
  primitiveLabel4: ["primitiveLabel4"],
  primitiveButton: ["primitiveButton", "primitiveSpan"],
  primitiveSpan: ["primitiveSpan"],
  container9: [
    "container9",
    "primitiveLabel5",
    "primitiveButton2",
    "primitiveSpan2"
  ],
  primitiveLabel5: ["primitiveLabel5"],
  primitiveButton2: ["primitiveButton2", "primitiveSpan2"],
  primitiveSpan2: ["primitiveSpan2"],
  container10: ["container10", "primitiveLabel6", "textarea"],
  primitiveLabel6: ["primitiveLabel6"],
  textarea: ["textarea"],
  button2: ["button2", "img"],
  img: ["img"],
  offices: [
    "offices",
    "container11",
    "container12",
    "experienceTheFutureOfLuxuryLivingAcrossAfri2",
    "section2",
    "card4",
    "texts3",
    "contactPage10",
    "subtext3",
    "contactPage11",
    "contactPage12",
    "contactPage13",
    "button3",
    "card5",
    "texts4",
    "contactPage14",
    "subtext4",
    "contactPage15",
    "contactPage16",
    "contactPage17",
    "button4",
    "card6",
    "texts5",
    "contactPage18",
    "subtext5",
    "contactPage19",
    "contactPage20",
    "contactPage21",
    "button5"
  ],
  container11: [
    "container11",
    "container12",
    "experienceTheFutureOfLuxuryLivingAcrossAfri2",
    "section2",
    "card4",
    "texts3",
    "contactPage10",
    "subtext3",
    "contactPage11",
    "contactPage12",
    "contactPage13",
    "button3",
    "card5",
    "texts4",
    "contactPage14",
    "subtext4",
    "contactPage15",
    "contactPage16",
    "contactPage17",
    "button4",
    "card6",
    "texts5",
    "contactPage18",
    "subtext5",
    "contactPage19",
    "contactPage20",
    "contactPage21",
    "button5"
  ],
  container12: ["container12", "experienceTheFutureOfLuxuryLivingAcrossAfri2"],
  experienceTheFutureOfLuxuryLivingAcrossAfri2: [
    "experienceTheFutureOfLuxuryLivingAcrossAfri2"
  ],
  section2: [
    "section2",
    "card4",
    "texts3",
    "contactPage10",
    "subtext3",
    "contactPage11",
    "contactPage12",
    "contactPage13",
    "button3",
    "card5",
    "texts4",
    "contactPage14",
    "subtext4",
    "contactPage15",
    "contactPage16",
    "contactPage17",
    "button4",
    "card6",
    "texts5",
    "contactPage18",
    "subtext5",
    "contactPage19",
    "contactPage20",
    "contactPage21",
    "button5"
  ],
  card4: [
    "card4",
    "texts3",
    "contactPage10",
    "subtext3",
    "contactPage11",
    "contactPage12",
    "contactPage13",
    "button3"
  ],
  texts3: [
    "texts3",
    "contactPage10",
    "subtext3",
    "contactPage11",
    "contactPage12",
    "contactPage13"
  ],
  contactPage10: ["contactPage10"],
  subtext3: ["subtext3", "contactPage11", "contactPage12", "contactPage13"],
  contactPage11: ["contactPage11"],
  contactPage12: ["contactPage12"],
  contactPage13: ["contactPage13"],
  button3: ["button3"],
  card5: [
    "card5",
    "texts4",
    "contactPage14",
    "subtext4",
    "contactPage15",
    "contactPage16",
    "contactPage17",
    "button4"
  ],
  texts4: [
    "texts4",
    "contactPage14",
    "subtext4",
    "contactPage15",
    "contactPage16",
    "contactPage17"
  ],
  contactPage14: ["contactPage14"],
  subtext4: ["subtext4", "contactPage15", "contactPage16", "contactPage17"],
  contactPage15: ["contactPage15"],
  contactPage16: ["contactPage16"],
  contactPage17: ["contactPage17"],
  button4: ["button4"],
  card6: [
    "card6",
    "texts5",
    "contactPage18",
    "subtext5",
    "contactPage19",
    "contactPage20",
    "contactPage21",
    "button5"
  ],
  texts5: [
    "texts5",
    "contactPage18",
    "subtext5",
    "contactPage19",
    "contactPage20",
    "contactPage21"
  ],
  contactPage18: ["contactPage18"],
  subtext5: ["subtext5", "contactPage19", "contactPage20", "contactPage21"],
  contactPage19: ["contactPage19"],
  contactPage20: ["contactPage20"],
  contactPage21: ["contactPage21"],
  button5: ["button5"],
  footer: [
    "footer",
    "container13",
    "left",
    "logo2",
    "logo3",
    "logoMark2",
    "texts6",
    "paragraph",
    "paragraph2",
    "right",
    "container14",
    "header2",
    "list",
    "listItem",
    "link6",
    "listItem2",
    "link7",
    "listItem3",
    "link8",
    "listItem4",
    "link9",
    "container15",
    "header3",
    "list2",
    "listItem5",
    "listItem6",
    "container16",
    "link10",
    "link11",
    "link12",
    "container17",
    "container18",
    "paragraph3",
    "_2025HouseNo5ByAfriNestAllRightsReserve",
    "container19",
    "text",
    "link13",
    "link14",
    "link15"
  ],
  container13: [
    "container13",
    "left",
    "logo2",
    "logo3",
    "logoMark2",
    "texts6",
    "paragraph",
    "paragraph2",
    "right",
    "container14",
    "header2",
    "list",
    "listItem",
    "link6",
    "listItem2",
    "link7",
    "listItem3",
    "link8",
    "listItem4",
    "link9",
    "container15",
    "header3",
    "list2",
    "listItem5",
    "listItem6",
    "container16",
    "link10",
    "link11",
    "link12"
  ],
  left: [
    "left",
    "logo2",
    "logo3",
    "logoMark2",
    "texts6",
    "paragraph",
    "paragraph2"
  ],
  logo2: ["logo2", "logo3", "logoMark2"],
  logo3: ["logo3", "logoMark2"],
  logoMark2: ["logoMark2"],
  texts6: ["texts6", "paragraph", "paragraph2"],
  paragraph: ["paragraph"],
  paragraph2: ["paragraph2"],
  right: [
    "right",
    "container14",
    "header2",
    "list",
    "listItem",
    "link6",
    "listItem2",
    "link7",
    "listItem3",
    "link8",
    "listItem4",
    "link9",
    "container15",
    "header3",
    "list2",
    "listItem5",
    "listItem6",
    "container16",
    "link10",
    "link11",
    "link12"
  ],
  container14: [
    "container14",
    "header2",
    "list",
    "listItem",
    "link6",
    "listItem2",
    "link7",
    "listItem3",
    "link8",
    "listItem4",
    "link9"
  ],
  header2: ["header2"],
  list: [
    "list",
    "listItem",
    "link6",
    "listItem2",
    "link7",
    "listItem3",
    "link8",
    "listItem4",
    "link9"
  ],
  listItem: ["listItem", "link6"],
  link6: ["link6"],
  listItem2: ["listItem2", "link7"],
  link7: ["link7"],
  listItem3: ["listItem3", "link8"],
  link8: ["link8"],
  listItem4: ["listItem4", "link9"],
  link9: ["link9"],
  container15: [
    "container15",
    "header3",
    "list2",
    "listItem5",
    "listItem6",
    "container16",
    "link10",
    "link11",
    "link12"
  ],
  header3: ["header3"],
  list2: ["list2", "listItem5", "listItem6"],
  listItem5: ["listItem5"],
  listItem6: ["listItem6"],
  container16: ["container16", "link10", "link11", "link12"],
  link10: ["link10"],
  link11: ["link11"],
  link12: ["link12"],
  container17: [
    "container17",
    "container18",
    "paragraph3",
    "_2025HouseNo5ByAfriNestAllRightsReserve",
    "container19",
    "text",
    "link13",
    "link14",
    "link15"
  ],
  container18: [
    "container18",
    "paragraph3",
    "_2025HouseNo5ByAfriNestAllRightsReserve",
    "container19",
    "text",
    "link13",
    "link14",
    "link15"
  ],
  paragraph3: ["paragraph3", "_2025HouseNo5ByAfriNestAllRightsReserve"],
  _2025HouseNo5ByAfriNestAllRightsReserve: [
    "_2025HouseNo5ByAfriNestAllRightsReserve"
  ],
  container19: ["container19", "text", "link13", "link14", "link15"],
  text: ["text"],
  link13: ["link13"],
  link14: ["link14"],
  link15: ["link15"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  contactPage: "div";
  headerHeroSection: "div";
  header: "div";
  container: "div";
  logo: "div";
  logoMark: "div";
  navigationMenu: "div";
  link: "div";
  link2: "div";
  link3: "div";
  link4: "div";
  link5: "div";
  button: "button";
  heroSection: "div";
  container2: "div";
  experienceTheFutureOfLuxuryLivingAcrossAfri: "div";
  section: "div";
  card: "div";
  texts: "div";
  contactPage2: "div";
  subtext: "div";
  contactPage3: "div";
  contactPage4: "div";
  card2: "div";
  texts2: "div";
  contactPage5: "div";
  subtext2: "div";
  contactPage6: "div";
  contactPage7: "div";
  sendUsMessage: "div";
  card3: "div";
  contactPage8: "div";
  contactPage9: "div";
  container3: "div";
  container4: "div";
  primitiveLabel: "div";
  input: "div";
  container5: "div";
  primitiveLabel2: "div";
  input2: "div";
  container6: "div";
  container7: "div";
  primitiveLabel3: "div";
  input3: "div";
  container8: "div";
  primitiveLabel4: "div";
  primitiveButton: "div";
  primitiveSpan: "div";
  container9: "div";
  primitiveLabel5: "div";
  primitiveButton2: "div";
  primitiveSpan2: "div";
  container10: "div";
  primitiveLabel6: "div";
  textarea: "div";
  button2: "div";
  img: typeof PlasmicImg__;
  offices: "div";
  container11: "div";
  container12: "div";
  experienceTheFutureOfLuxuryLivingAcrossAfri2: "div";
  section2: "div";
  card4: "div";
  texts3: "div";
  contactPage10: "div";
  subtext3: "div";
  contactPage11: "div";
  contactPage12: "div";
  contactPage13: "div";
  button3: "div";
  card5: "div";
  texts4: "div";
  contactPage14: "div";
  subtext4: "div";
  contactPage15: "div";
  contactPage16: "div";
  contactPage17: "div";
  button4: "button";
  card6: "div";
  texts5: "div";
  contactPage18: "div";
  subtext5: "div";
  contactPage19: "div";
  contactPage20: "div";
  contactPage21: "div";
  button5: "button";
  footer: "div";
  container13: "div";
  left: "div";
  logo2: "div";
  logo3: "div";
  logoMark2: "div";
  texts6: "div";
  paragraph: "div";
  paragraph2: "div";
  right: "div";
  container14: "div";
  header2: "div";
  list: "div";
  listItem: "div";
  link6: "div";
  listItem2: "div";
  link7: "div";
  listItem3: "div";
  link8: "div";
  listItem4: "div";
  link9: "div";
  container15: "div";
  header3: "div";
  list2: "div";
  listItem5: "div";
  listItem6: "div";
  container16: "div";
  link10: "div";
  link11: "div";
  link12: "div";
  container17: "div";
  container18: "div";
  paragraph3: "div";
  _2025HouseNo5ByAfriNestAllRightsReserve: "div";
  container19: "div";
  text: "div";
  link13: "div";
  link14: "div";
  link15: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicContact__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicContact__VariantsArgs;
    args?: PlasmicContact__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicContact__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicContact__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicContact__ArgProps,
          internalVariantPropNames: PlasmicContact__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicContact__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicContact";
  } else {
    func.displayName = `PlasmicContact.${nodeName}`;
  }
  return func;
}

export const PlasmicContact = Object.assign(
  // Top-level PlasmicContact renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    contactPage: makeNodeComponent("contactPage"),
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    header: makeNodeComponent("header"),
    container: makeNodeComponent("container"),
    logo: makeNodeComponent("logo"),
    logoMark: makeNodeComponent("logoMark"),
    navigationMenu: makeNodeComponent("navigationMenu"),
    link: makeNodeComponent("link"),
    link2: makeNodeComponent("link2"),
    link3: makeNodeComponent("link3"),
    link4: makeNodeComponent("link4"),
    link5: makeNodeComponent("link5"),
    button: makeNodeComponent("button"),
    heroSection: makeNodeComponent("heroSection"),
    container2: makeNodeComponent("container2"),
    experienceTheFutureOfLuxuryLivingAcrossAfri: makeNodeComponent(
      "experienceTheFutureOfLuxuryLivingAcrossAfri"
    ),
    section: makeNodeComponent("section"),
    card: makeNodeComponent("card"),
    texts: makeNodeComponent("texts"),
    contactPage2: makeNodeComponent("contactPage2"),
    subtext: makeNodeComponent("subtext"),
    contactPage3: makeNodeComponent("contactPage3"),
    contactPage4: makeNodeComponent("contactPage4"),
    card2: makeNodeComponent("card2"),
    texts2: makeNodeComponent("texts2"),
    contactPage5: makeNodeComponent("contactPage5"),
    subtext2: makeNodeComponent("subtext2"),
    contactPage6: makeNodeComponent("contactPage6"),
    contactPage7: makeNodeComponent("contactPage7"),
    sendUsMessage: makeNodeComponent("sendUsMessage"),
    card3: makeNodeComponent("card3"),
    contactPage8: makeNodeComponent("contactPage8"),
    contactPage9: makeNodeComponent("contactPage9"),
    container3: makeNodeComponent("container3"),
    container4: makeNodeComponent("container4"),
    primitiveLabel: makeNodeComponent("primitiveLabel"),
    input: makeNodeComponent("input"),
    container5: makeNodeComponent("container5"),
    primitiveLabel2: makeNodeComponent("primitiveLabel2"),
    input2: makeNodeComponent("input2"),
    container6: makeNodeComponent("container6"),
    container7: makeNodeComponent("container7"),
    primitiveLabel3: makeNodeComponent("primitiveLabel3"),
    input3: makeNodeComponent("input3"),
    container8: makeNodeComponent("container8"),
    primitiveLabel4: makeNodeComponent("primitiveLabel4"),
    primitiveButton: makeNodeComponent("primitiveButton"),
    primitiveSpan: makeNodeComponent("primitiveSpan"),
    container9: makeNodeComponent("container9"),
    primitiveLabel5: makeNodeComponent("primitiveLabel5"),
    primitiveButton2: makeNodeComponent("primitiveButton2"),
    primitiveSpan2: makeNodeComponent("primitiveSpan2"),
    container10: makeNodeComponent("container10"),
    primitiveLabel6: makeNodeComponent("primitiveLabel6"),
    textarea: makeNodeComponent("textarea"),
    button2: makeNodeComponent("button2"),
    img: makeNodeComponent("img"),
    offices: makeNodeComponent("offices"),
    container11: makeNodeComponent("container11"),
    container12: makeNodeComponent("container12"),
    experienceTheFutureOfLuxuryLivingAcrossAfri2: makeNodeComponent(
      "experienceTheFutureOfLuxuryLivingAcrossAfri2"
    ),
    section2: makeNodeComponent("section2"),
    card4: makeNodeComponent("card4"),
    texts3: makeNodeComponent("texts3"),
    contactPage10: makeNodeComponent("contactPage10"),
    subtext3: makeNodeComponent("subtext3"),
    contactPage11: makeNodeComponent("contactPage11"),
    contactPage12: makeNodeComponent("contactPage12"),
    contactPage13: makeNodeComponent("contactPage13"),
    button3: makeNodeComponent("button3"),
    card5: makeNodeComponent("card5"),
    texts4: makeNodeComponent("texts4"),
    contactPage14: makeNodeComponent("contactPage14"),
    subtext4: makeNodeComponent("subtext4"),
    contactPage15: makeNodeComponent("contactPage15"),
    contactPage16: makeNodeComponent("contactPage16"),
    contactPage17: makeNodeComponent("contactPage17"),
    button4: makeNodeComponent("button4"),
    card6: makeNodeComponent("card6"),
    texts5: makeNodeComponent("texts5"),
    contactPage18: makeNodeComponent("contactPage18"),
    subtext5: makeNodeComponent("subtext5"),
    contactPage19: makeNodeComponent("contactPage19"),
    contactPage20: makeNodeComponent("contactPage20"),
    contactPage21: makeNodeComponent("contactPage21"),
    button5: makeNodeComponent("button5"),
    footer: makeNodeComponent("footer"),
    container13: makeNodeComponent("container13"),
    left: makeNodeComponent("left"),
    logo2: makeNodeComponent("logo2"),
    logo3: makeNodeComponent("logo3"),
    logoMark2: makeNodeComponent("logoMark2"),
    texts6: makeNodeComponent("texts6"),
    paragraph: makeNodeComponent("paragraph"),
    paragraph2: makeNodeComponent("paragraph2"),
    right: makeNodeComponent("right"),
    container14: makeNodeComponent("container14"),
    header2: makeNodeComponent("header2"),
    list: makeNodeComponent("list"),
    listItem: makeNodeComponent("listItem"),
    link6: makeNodeComponent("link6"),
    listItem2: makeNodeComponent("listItem2"),
    link7: makeNodeComponent("link7"),
    listItem3: makeNodeComponent("listItem3"),
    link8: makeNodeComponent("link8"),
    listItem4: makeNodeComponent("listItem4"),
    link9: makeNodeComponent("link9"),
    container15: makeNodeComponent("container15"),
    header3: makeNodeComponent("header3"),
    list2: makeNodeComponent("list2"),
    listItem5: makeNodeComponent("listItem5"),
    listItem6: makeNodeComponent("listItem6"),
    container16: makeNodeComponent("container16"),
    link10: makeNodeComponent("link10"),
    link11: makeNodeComponent("link11"),
    link12: makeNodeComponent("link12"),
    container17: makeNodeComponent("container17"),
    container18: makeNodeComponent("container18"),
    paragraph3: makeNodeComponent("paragraph3"),
    _2025HouseNo5ByAfriNestAllRightsReserve: makeNodeComponent(
      "_2025HouseNo5ByAfriNestAllRightsReserve"
    ),
    container19: makeNodeComponent("container19"),
    text: makeNodeComponent("text"),
    link13: makeNodeComponent("link13"),
    link14: makeNodeComponent("link14"),
    link15: makeNodeComponent("link15"),

    // Metadata about props expected for PlasmicContact
    internalVariantProps: PlasmicContact__VariantProps,
    internalArgProps: PlasmicContact__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicContact;
/* prettier-ignore-end */
