/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: onkH1pA6HdPM1JMb3Mte45

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantspRtsKqIoXui } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: PRtsKqIo_XUI/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantspRtsKqIoXui
});
