/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: onkH1pA6HdPM1JMb3Mte45
// Component: 6MIsCD7pFLpn

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/projectcss
import sty from "./PlasmicSignup.module.css"; // plasmic-import: 6MIsCD7pFLpn/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: EB1OGIZsE2Kn/icon

createPlasmicElementProxy;

export type PlasmicSignup__VariantMembers = {};
export type PlasmicSignup__VariantsArgs = {};
type VariantPropType = keyof PlasmicSignup__VariantsArgs;
export const PlasmicSignup__VariantProps = new Array<VariantPropType>();

export type PlasmicSignup__ArgsType = {};
type ArgPropType = keyof PlasmicSignup__ArgsType;
export const PlasmicSignup__ArgProps = new Array<ArgPropType>();

export type PlasmicSignup__OverridesType = {
  root?: Flex__<"div">;
  signup?: Flex__<"div">;
  container?: Flex__<"div">;
  image?: Flex__<"div">;
  content?: Flex__<"div">;
  title?: Flex__<"div">;
  form?: Flex__<"div">;
  input?: Flex__<"div">;
  container2?: Flex__<"div">;
  primitiveLabel?: Flex__<"div">;
  input2?: Flex__<"div">;
  container3?: Flex__<"div">;
  primitiveLabel2?: Flex__<"div">;
  input3?: Flex__<"div">;
  container4?: Flex__<"div">;
  primitiveLabel3?: Flex__<"div">;
  input4?: Flex__<"div">;
  code?: Flex__<"div">;
  svg?: Flex__<"svg">;
  container5?: Flex__<"div">;
  primitiveLabel4?: Flex__<"div">;
  input5?: Flex__<"div">;
  button?: Flex__<"div">;
  secondaryAction?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultSignupProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSignup__RenderFunc(props: {
  variants: PlasmicSignup__VariantsArgs;
  args: PlasmicSignup__ArgsType;
  overrides: PlasmicSignup__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"signup"}
            data-plasmic-override={overrides.signup}
            className={classNames(projectcss.all, sty.signup)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames(projectcss.all, sty.container)}
            >
              <div
                data-plasmic-name={"image"}
                data-plasmic-override={overrides.image}
                className={classNames(projectcss.all, sty.image)}
              />

              <div
                data-plasmic-name={"content"}
                data-plasmic-override={overrides.content}
                className={classNames(projectcss.all, sty.content)}
              >
                <div
                  data-plasmic-name={"title"}
                  data-plasmic-override={overrides.title}
                  className={classNames(projectcss.all, sty.title)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5Rxvi
                    )}
                  >
                    {"Welcome to House No.5"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tdNgm
                    )}
                  >
                    {"Register your account."}
                  </div>
                </div>
                <div
                  data-plasmic-name={"form"}
                  data-plasmic-override={overrides.form}
                  className={classNames(projectcss.all, sty.form)}
                >
                  <div
                    data-plasmic-name={"input"}
                    data-plasmic-override={overrides.input}
                    className={classNames(projectcss.all, sty.input)}
                  >
                    <div
                      data-plasmic-name={"container2"}
                      data-plasmic-override={overrides.container2}
                      className={classNames(projectcss.all, sty.container2)}
                    >
                      <div
                        data-plasmic-name={"primitiveLabel"}
                        data-plasmic-override={overrides.primitiveLabel}
                        className={classNames(
                          projectcss.all,
                          sty.primitiveLabel
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__oGcx6
                          )}
                        >
                          {"Full Name *"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"input2"}
                        data-plasmic-override={overrides.input2}
                        className={classNames(projectcss.all, sty.input2)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__k9R4H
                          )}
                        >
                          {"John Doe"}
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"container3"}
                      data-plasmic-override={overrides.container3}
                      className={classNames(projectcss.all, sty.container3)}
                    >
                      <div
                        data-plasmic-name={"primitiveLabel2"}
                        data-plasmic-override={overrides.primitiveLabel2}
                        className={classNames(
                          projectcss.all,
                          sty.primitiveLabel2
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dAn45
                          )}
                        >
                          {"Email Address *"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"input3"}
                        data-plasmic-override={overrides.input3}
                        className={classNames(projectcss.all, sty.input3)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fovc
                          )}
                        >
                          {"name@example.com"}
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"container4"}
                      data-plasmic-override={overrides.container4}
                      className={classNames(projectcss.all, sty.container4)}
                    >
                      <div
                        data-plasmic-name={"primitiveLabel3"}
                        data-plasmic-override={overrides.primitiveLabel3}
                        className={classNames(
                          projectcss.all,
                          sty.primitiveLabel3
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qSh5L
                          )}
                        >
                          {"Phone Number"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"input4"}
                        data-plasmic-override={overrides.input4}
                        className={classNames(projectcss.all, sty.input4)}
                      >
                        <div
                          data-plasmic-name={"code"}
                          data-plasmic-override={overrides.code}
                          className={classNames(projectcss.all, sty.code)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zdAeS
                            )}
                          >
                            {"+234"}
                          </div>
                          <IconIcon
                            data-plasmic-name={"svg"}
                            data-plasmic-override={overrides.svg}
                            className={classNames(projectcss.all, sty.svg)}
                            role={"img"}
                          />
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dUko0
                          )}
                        >
                          {"phone number"}
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"container5"}
                      data-plasmic-override={overrides.container5}
                      className={classNames(projectcss.all, sty.container5)}
                    >
                      <div
                        data-plasmic-name={"primitiveLabel4"}
                        data-plasmic-override={overrides.primitiveLabel4}
                        className={classNames(
                          projectcss.all,
                          sty.primitiveLabel4
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__g8Lmw
                          )}
                        >
                          {"Password *"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"input5"}
                        data-plasmic-override={overrides.input5}
                        className={classNames(projectcss.all, sty.input5)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__czE4
                          )}
                        >
                          {"************"}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames(projectcss.all, sty.button)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uyj27
                    )}
                  >
                    {"Register account"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"secondaryAction"}
                  data-plasmic-override={overrides.secondaryAction}
                  className={classNames(projectcss.all, sty.secondaryAction)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oSfm4
                    )}
                  >
                    {"Existing User?"}
                  </div>
                  <PlasmicLink__
                    data-plasmic-name={"link"}
                    data-plasmic-override={overrides.link}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link
                    )}
                    component={Link}
                    href={`/login`}
                    platform={"nextjs"}
                  >
                    {"Login"}
                  </PlasmicLink__>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "signup",
    "container",
    "image",
    "content",
    "title",
    "form",
    "input",
    "container2",
    "primitiveLabel",
    "input2",
    "container3",
    "primitiveLabel2",
    "input3",
    "container4",
    "primitiveLabel3",
    "input4",
    "code",
    "svg",
    "container5",
    "primitiveLabel4",
    "input5",
    "button",
    "secondaryAction",
    "link"
  ],
  signup: [
    "signup",
    "container",
    "image",
    "content",
    "title",
    "form",
    "input",
    "container2",
    "primitiveLabel",
    "input2",
    "container3",
    "primitiveLabel2",
    "input3",
    "container4",
    "primitiveLabel3",
    "input4",
    "code",
    "svg",
    "container5",
    "primitiveLabel4",
    "input5",
    "button",
    "secondaryAction",
    "link"
  ],
  container: [
    "container",
    "image",
    "content",
    "title",
    "form",
    "input",
    "container2",
    "primitiveLabel",
    "input2",
    "container3",
    "primitiveLabel2",
    "input3",
    "container4",
    "primitiveLabel3",
    "input4",
    "code",
    "svg",
    "container5",
    "primitiveLabel4",
    "input5",
    "button",
    "secondaryAction",
    "link"
  ],
  image: ["image"],
  content: [
    "content",
    "title",
    "form",
    "input",
    "container2",
    "primitiveLabel",
    "input2",
    "container3",
    "primitiveLabel2",
    "input3",
    "container4",
    "primitiveLabel3",
    "input4",
    "code",
    "svg",
    "container5",
    "primitiveLabel4",
    "input5",
    "button",
    "secondaryAction",
    "link"
  ],
  title: ["title"],
  form: [
    "form",
    "input",
    "container2",
    "primitiveLabel",
    "input2",
    "container3",
    "primitiveLabel2",
    "input3",
    "container4",
    "primitiveLabel3",
    "input4",
    "code",
    "svg",
    "container5",
    "primitiveLabel4",
    "input5"
  ],
  input: [
    "input",
    "container2",
    "primitiveLabel",
    "input2",
    "container3",
    "primitiveLabel2",
    "input3",
    "container4",
    "primitiveLabel3",
    "input4",
    "code",
    "svg",
    "container5",
    "primitiveLabel4",
    "input5"
  ],
  container2: ["container2", "primitiveLabel", "input2"],
  primitiveLabel: ["primitiveLabel"],
  input2: ["input2"],
  container3: ["container3", "primitiveLabel2", "input3"],
  primitiveLabel2: ["primitiveLabel2"],
  input3: ["input3"],
  container4: ["container4", "primitiveLabel3", "input4", "code", "svg"],
  primitiveLabel3: ["primitiveLabel3"],
  input4: ["input4", "code", "svg"],
  code: ["code", "svg"],
  svg: ["svg"],
  container5: ["container5", "primitiveLabel4", "input5"],
  primitiveLabel4: ["primitiveLabel4"],
  input5: ["input5"],
  button: ["button"],
  secondaryAction: ["secondaryAction", "link"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  signup: "div";
  container: "div";
  image: "div";
  content: "div";
  title: "div";
  form: "div";
  input: "div";
  container2: "div";
  primitiveLabel: "div";
  input2: "div";
  container3: "div";
  primitiveLabel2: "div";
  input3: "div";
  container4: "div";
  primitiveLabel3: "div";
  input4: "div";
  code: "div";
  svg: "svg";
  container5: "div";
  primitiveLabel4: "div";
  input5: "div";
  button: "div";
  secondaryAction: "div";
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSignup__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSignup__VariantsArgs;
    args?: PlasmicSignup__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSignup__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSignup__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSignup__ArgProps,
          internalVariantPropNames: PlasmicSignup__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSignup__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSignup";
  } else {
    func.displayName = `PlasmicSignup.${nodeName}`;
  }
  return func;
}

export const PlasmicSignup = Object.assign(
  // Top-level PlasmicSignup renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    signup: makeNodeComponent("signup"),
    container: makeNodeComponent("container"),
    image: makeNodeComponent("image"),
    content: makeNodeComponent("content"),
    title: makeNodeComponent("title"),
    form: makeNodeComponent("form"),
    input: makeNodeComponent("input"),
    container2: makeNodeComponent("container2"),
    primitiveLabel: makeNodeComponent("primitiveLabel"),
    input2: makeNodeComponent("input2"),
    container3: makeNodeComponent("container3"),
    primitiveLabel2: makeNodeComponent("primitiveLabel2"),
    input3: makeNodeComponent("input3"),
    container4: makeNodeComponent("container4"),
    primitiveLabel3: makeNodeComponent("primitiveLabel3"),
    input4: makeNodeComponent("input4"),
    code: makeNodeComponent("code"),
    svg: makeNodeComponent("svg"),
    container5: makeNodeComponent("container5"),
    primitiveLabel4: makeNodeComponent("primitiveLabel4"),
    input5: makeNodeComponent("input5"),
    button: makeNodeComponent("button"),
    secondaryAction: makeNodeComponent("secondaryAction"),
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicSignup
    internalVariantProps: PlasmicSignup__VariantProps,
    internalArgProps: PlasmicSignup__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSignup;
/* prettier-ignore-end */
