/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: onkH1pA6HdPM1JMb3Mte45
// Component: pcoSRbQO_r8-

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/projectcss
import sty from "./Plasmic_3DWalkthrough.module.css"; // plasmic-import: pcoSRbQO_r8-/css

import Vector1Icon from "./icons/PlasmicIcon__Vector1"; // plasmic-import: f68eVSSD6GHl/icon
import Icon7Icon from "./icons/PlasmicIcon__Icon7"; // plasmic-import: 6qGWRE-38yD0/icon
import Arrow2Icon from "./icons/PlasmicIcon__Arrow2"; // plasmic-import: SXieq0M2bzak/icon
import ArrowIcon from "./icons/PlasmicIcon__Arrow"; // plasmic-import: LrzIpY4AIRk_/icon

createPlasmicElementProxy;

export type Plasmic_3DWalkthrough__VariantMembers = {};
export type Plasmic_3DWalkthrough__VariantsArgs = {};
type VariantPropType = keyof Plasmic_3DWalkthrough__VariantsArgs;
export const Plasmic_3DWalkthrough__VariantProps = new Array<VariantPropType>();

export type Plasmic_3DWalkthrough__ArgsType = {};
type ArgPropType = keyof Plasmic_3DWalkthrough__ArgsType;
export const Plasmic_3DWalkthrough__ArgProps = new Array<ArgPropType>();

export type Plasmic_3DWalkthrough__OverridesType = {
  root?: Flex__<"div">;
  _3DWalkthrough?: Flex__<"div">;
  halfBg?: Flex__<"div">;
  halfBg2?: Flex__<"div">;
  results?: Flex__<"div">;
  title?: Flex__<"div">;
  badge?: Flex__<"div">;
  content?: Flex__<"div">;
  tabs?: Flex__<"div">;
  tab?: Flex__<"div">;
  title2?: Flex__<"div">;
  options?: Flex__<"div">;
  _1?: Flex__<"div">;
  _2?: Flex__<"div">;
  _3?: Flex__<"div">;
  button?: Flex__<"div">;
  cards?: Flex__<"div">;
  card?: Flex__<"div">;
  imageWithFallback?: Flex__<"div">;
  viewMore?: Flex__<"div">;
  pagination?: Flex__<"div">;
  number?: Flex__<"div">;
  _4?: Flex__<"div">;
  _5?: Flex__<"div">;
  _6?: Flex__<"div">;
  _7?: Flex__<"div">;
  freeBox?: Flex__<"div">;
};

export interface Default_3DWalkthroughProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function Plasmic_3DWalkthrough__RenderFunc(props: {
  variants: Plasmic_3DWalkthrough__VariantsArgs;
  args: Plasmic_3DWalkthrough__ArgsType;
  overrides: Plasmic_3DWalkthrough__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"_3DWalkthrough"}
            data-plasmic-override={overrides._3DWalkthrough}
            className={classNames(projectcss.all, sty._3DWalkthrough)}
          >
            <div
              data-plasmic-name={"halfBg"}
              data-plasmic-override={overrides.halfBg}
              className={classNames(projectcss.all, sty.halfBg)}
            />

            <div
              data-plasmic-name={"halfBg2"}
              data-plasmic-override={overrides.halfBg2}
              className={classNames(projectcss.all, sty.halfBg2)}
            />

            <div
              data-plasmic-name={"results"}
              data-plasmic-override={overrides.results}
              className={classNames(projectcss.all, sty.results)}
            >
              <div
                data-plasmic-name={"title"}
                data-plasmic-override={overrides.title}
                className={classNames(projectcss.all, sty.title)}
              >
                <div
                  data-plasmic-name={"badge"}
                  data-plasmic-override={overrides.badge}
                  className={classNames(projectcss.all, sty.badge)}
                >
                  <Vector1Icon
                    className={classNames(projectcss.all, sty.svg___4K2Iq)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__stA5C
                    )}
                  >
                    {"Floorplans + 3D Walkthroughs"}
                  </div>
                </div>
                {false ? (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3EgG
                    )}
                  >
                    {"Nigeria Developments"}
                  </div>
                ) : null}
              </div>
              <div
                data-plasmic-name={"content"}
                data-plasmic-override={overrides.content}
                className={classNames(projectcss.all, sty.content)}
              >
                <div
                  data-plasmic-name={"tabs"}
                  data-plasmic-override={overrides.tabs}
                  className={classNames(projectcss.all, sty.tabs)}
                >
                  <div
                    data-plasmic-name={"tab"}
                    data-plasmic-override={overrides.tab}
                    className={classNames(projectcss.all, sty.tab)}
                  >
                    <div
                      data-plasmic-name={"title2"}
                      data-plasmic-override={overrides.title2}
                      className={classNames(projectcss.all, sty.title2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__k6KJj
                        )}
                      >
                        {"Options"}
                      </div>
                      <Icon7Icon
                        className={classNames(projectcss.all, sty.svg__lXwtl)}
                        role={"img"}
                      />
                    </div>
                    <div
                      data-plasmic-name={"options"}
                      data-plasmic-override={overrides.options}
                      className={classNames(projectcss.all, sty.options)}
                    >
                      <div
                        data-plasmic-name={"_1"}
                        data-plasmic-override={overrides._1}
                        className={classNames(projectcss.all, sty._1)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wRnH
                          )}
                        >
                          {"Floorplans"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"_2"}
                        data-plasmic-override={overrides._2}
                        className={classNames(projectcss.all, sty._2)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fpU
                          )}
                        >
                          {"3D walkthrough"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"_3"}
                        data-plasmic-override={overrides._3}
                        className={classNames(projectcss.all, sty._3)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__iBaka
                          )}
                        >
                          {"Smart features"}
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"button"}
                      data-plasmic-override={overrides.button}
                      className={classNames(projectcss.all, sty.button)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nq3Rn
                        )}
                      >
                        {"Make Enquiry"}
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"cards"}
                  data-plasmic-override={overrides.cards}
                  className={classNames(projectcss.all, sty.cards)}
                >
                  <div
                    data-plasmic-name={"card"}
                    data-plasmic-override={overrides.card}
                    className={classNames(projectcss.all, sty.card)}
                  >
                    <div
                      data-plasmic-name={"imageWithFallback"}
                      data-plasmic-override={overrides.imageWithFallback}
                      className={classNames(
                        projectcss.all,
                        sty.imageWithFallback
                      )}
                    />

                    <div
                      data-plasmic-name={"viewMore"}
                      data-plasmic-override={overrides.viewMore}
                      className={classNames(projectcss.all, sty.viewMore)}
                    >
                      <div
                        data-plasmic-name={"pagination"}
                        data-plasmic-override={overrides.pagination}
                        className={classNames(projectcss.all, sty.pagination)}
                      >
                        <Arrow2Icon
                          className={classNames(projectcss.all, sty.svg__vBooe)}
                          role={"img"}
                        />

                        <div
                          data-plasmic-name={"number"}
                          data-plasmic-override={overrides.number}
                          className={classNames(projectcss.all, sty.number)}
                        >
                          <div
                            data-plasmic-name={"_4"}
                            data-plasmic-override={overrides._4}
                            className={classNames(projectcss.all, sty._4)}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__tyHmO
                                )}
                              >
                                {"1"}
                              </div>
                            ) : null}
                          </div>
                          <div
                            data-plasmic-name={"_5"}
                            data-plasmic-override={overrides._5}
                            className={classNames(projectcss.all, sty._5)}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__pbDqR
                                )}
                              >
                                {"2"}
                              </div>
                            ) : null}
                          </div>
                          <div
                            data-plasmic-name={"_6"}
                            data-plasmic-override={overrides._6}
                            className={classNames(projectcss.all, sty._6)}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__glnIi
                                )}
                              >
                                {"3"}
                              </div>
                            ) : null}
                          </div>
                          <div
                            data-plasmic-name={"_7"}
                            data-plasmic-override={overrides._7}
                            className={classNames(projectcss.all, sty._7)}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__s2DNs
                                )}
                              >
                                {"3"}
                              </div>
                            ) : null}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"freeBox"}
                          data-plasmic-override={overrides.freeBox}
                          className={classNames(projectcss.all, sty.freeBox)}
                        >
                          <ArrowIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__xuafm
                            )}
                            role={"img"}
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "_3DWalkthrough",
    "halfBg",
    "halfBg2",
    "results",
    "title",
    "badge",
    "content",
    "tabs",
    "tab",
    "title2",
    "options",
    "_1",
    "_2",
    "_3",
    "button",
    "cards",
    "card",
    "imageWithFallback",
    "viewMore",
    "pagination",
    "number",
    "_4",
    "_5",
    "_6",
    "_7",
    "freeBox"
  ],
  _3DWalkthrough: [
    "_3DWalkthrough",
    "halfBg",
    "halfBg2",
    "results",
    "title",
    "badge",
    "content",
    "tabs",
    "tab",
    "title2",
    "options",
    "_1",
    "_2",
    "_3",
    "button",
    "cards",
    "card",
    "imageWithFallback",
    "viewMore",
    "pagination",
    "number",
    "_4",
    "_5",
    "_6",
    "_7",
    "freeBox"
  ],
  halfBg: ["halfBg"],
  halfBg2: ["halfBg2"],
  results: [
    "results",
    "title",
    "badge",
    "content",
    "tabs",
    "tab",
    "title2",
    "options",
    "_1",
    "_2",
    "_3",
    "button",
    "cards",
    "card",
    "imageWithFallback",
    "viewMore",
    "pagination",
    "number",
    "_4",
    "_5",
    "_6",
    "_7",
    "freeBox"
  ],
  title: ["title", "badge"],
  badge: ["badge"],
  content: [
    "content",
    "tabs",
    "tab",
    "title2",
    "options",
    "_1",
    "_2",
    "_3",
    "button",
    "cards",
    "card",
    "imageWithFallback",
    "viewMore",
    "pagination",
    "number",
    "_4",
    "_5",
    "_6",
    "_7",
    "freeBox"
  ],
  tabs: ["tabs", "tab", "title2", "options", "_1", "_2", "_3", "button"],
  tab: ["tab", "title2", "options", "_1", "_2", "_3", "button"],
  title2: ["title2"],
  options: ["options", "_1", "_2", "_3"],
  _1: ["_1"],
  _2: ["_2"],
  _3: ["_3"],
  button: ["button"],
  cards: [
    "cards",
    "card",
    "imageWithFallback",
    "viewMore",
    "pagination",
    "number",
    "_4",
    "_5",
    "_6",
    "_7",
    "freeBox"
  ],
  card: [
    "card",
    "imageWithFallback",
    "viewMore",
    "pagination",
    "number",
    "_4",
    "_5",
    "_6",
    "_7",
    "freeBox"
  ],
  imageWithFallback: ["imageWithFallback"],
  viewMore: [
    "viewMore",
    "pagination",
    "number",
    "_4",
    "_5",
    "_6",
    "_7",
    "freeBox"
  ],
  pagination: ["pagination", "number", "_4", "_5", "_6", "_7", "freeBox"],
  number: ["number", "_4", "_5", "_6", "_7"],
  _4: ["_4"],
  _5: ["_5"],
  _6: ["_6"],
  _7: ["_7"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  _3DWalkthrough: "div";
  halfBg: "div";
  halfBg2: "div";
  results: "div";
  title: "div";
  badge: "div";
  content: "div";
  tabs: "div";
  tab: "div";
  title2: "div";
  options: "div";
  _1: "div";
  _2: "div";
  _3: "div";
  button: "div";
  cards: "div";
  card: "div";
  imageWithFallback: "div";
  viewMore: "div";
  pagination: "div";
  number: "div";
  _4: "div";
  _5: "div";
  _6: "div";
  _7: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmic_3DWalkthrough__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmic_3DWalkthrough__VariantsArgs;
    args?: Plasmic_3DWalkthrough__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<Plasmic_3DWalkthrough__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<Plasmic_3DWalkthrough__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: Plasmic_3DWalkthrough__ArgProps,
          internalVariantPropNames: Plasmic_3DWalkthrough__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmic_3DWalkthrough__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic_3DWalkthrough";
  } else {
    func.displayName = `Plasmic_3DWalkthrough.${nodeName}`;
  }
  return func;
}

export const Plasmic_3DWalkthrough = Object.assign(
  // Top-level Plasmic_3DWalkthrough renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    _3DWalkthrough: makeNodeComponent("_3DWalkthrough"),
    halfBg: makeNodeComponent("halfBg"),
    halfBg2: makeNodeComponent("halfBg2"),
    results: makeNodeComponent("results"),
    title: makeNodeComponent("title"),
    badge: makeNodeComponent("badge"),
    content: makeNodeComponent("content"),
    tabs: makeNodeComponent("tabs"),
    tab: makeNodeComponent("tab"),
    title2: makeNodeComponent("title2"),
    options: makeNodeComponent("options"),
    _1: makeNodeComponent("_1"),
    _2: makeNodeComponent("_2"),
    _3: makeNodeComponent("_3"),
    button: makeNodeComponent("button"),
    cards: makeNodeComponent("cards"),
    card: makeNodeComponent("card"),
    imageWithFallback: makeNodeComponent("imageWithFallback"),
    viewMore: makeNodeComponent("viewMore"),
    pagination: makeNodeComponent("pagination"),
    number: makeNodeComponent("number"),
    _4: makeNodeComponent("_4"),
    _5: makeNodeComponent("_5"),
    _6: makeNodeComponent("_6"),
    _7: makeNodeComponent("_7"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for Plasmic_3DWalkthrough
    internalVariantProps: Plasmic_3DWalkthrough__VariantProps,
    internalArgProps: Plasmic_3DWalkthrough__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default Plasmic_3DWalkthrough;
/* prettier-ignore-end */
