/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: onkH1pA6HdPM1JMb3Mte45
// Component: Q8qvI64rV4Oi

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/projectcss
import sty from "./PlasmicLogin.module.css"; // plasmic-import: Q8qvI64rV4Oi/css

createPlasmicElementProxy;

export type PlasmicLogin__VariantMembers = {};
export type PlasmicLogin__VariantsArgs = {};
type VariantPropType = keyof PlasmicLogin__VariantsArgs;
export const PlasmicLogin__VariantProps = new Array<VariantPropType>();

export type PlasmicLogin__ArgsType = {};
type ArgPropType = keyof PlasmicLogin__ArgsType;
export const PlasmicLogin__ArgProps = new Array<ArgPropType>();

export type PlasmicLogin__OverridesType = {
  root?: Flex__<"div">;
  logIn?: Flex__<"div">;
  container?: Flex__<"div">;
  image?: Flex__<"div">;
  content?: Flex__<"div">;
  title?: Flex__<"div">;
  form?: Flex__<"div">;
  input?: Flex__<"div">;
  container2?: Flex__<"div">;
  primitiveLabel?: Flex__<"div">;
  input2?: Flex__<"div">;
  container3?: Flex__<"div">;
  primitiveLabel2?: Flex__<"div">;
  input3?: Flex__<"div">;
  forgotPassword?: Flex__<"div">;
  button?: Flex__<"div">;
  secondaryAction?: Flex__<"div">;
};

export interface DefaultLoginProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLogin__RenderFunc(props: {
  variants: PlasmicLogin__VariantsArgs;
  args: PlasmicLogin__ArgsType;
  overrides: PlasmicLogin__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"logIn"}
            data-plasmic-override={overrides.logIn}
            className={classNames(projectcss.all, sty.logIn)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames(projectcss.all, sty.container)}
            >
              <div
                data-plasmic-name={"image"}
                data-plasmic-override={overrides.image}
                className={classNames(projectcss.all, sty.image)}
              />

              <div
                data-plasmic-name={"content"}
                data-plasmic-override={overrides.content}
                className={classNames(projectcss.all, sty.content)}
              >
                <div
                  data-plasmic-name={"title"}
                  data-plasmic-override={overrides.title}
                  className={classNames(projectcss.all, sty.title)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kgL5E
                    )}
                  >
                    {"Login"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jk2K8
                    )}
                  >
                    {"Welcome back! Please login to your account."}
                  </div>
                </div>
                <div
                  data-plasmic-name={"form"}
                  data-plasmic-override={overrides.form}
                  className={classNames(projectcss.all, sty.form)}
                >
                  <div
                    data-plasmic-name={"input"}
                    data-plasmic-override={overrides.input}
                    className={classNames(projectcss.all, sty.input)}
                  >
                    <div
                      data-plasmic-name={"container2"}
                      data-plasmic-override={overrides.container2}
                      className={classNames(projectcss.all, sty.container2)}
                    >
                      <div
                        data-plasmic-name={"primitiveLabel"}
                        data-plasmic-override={overrides.primitiveLabel}
                        className={classNames(
                          projectcss.all,
                          sty.primitiveLabel
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ooR9R
                          )}
                        >
                          {"Email Address *"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"input2"}
                        data-plasmic-override={overrides.input2}
                        className={classNames(projectcss.all, sty.input2)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tq41T
                          )}
                        >
                          {"name@example.com"}
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"container3"}
                      data-plasmic-override={overrides.container3}
                      className={classNames(projectcss.all, sty.container3)}
                    >
                      <div
                        data-plasmic-name={"primitiveLabel2"}
                        data-plasmic-override={overrides.primitiveLabel2}
                        className={classNames(
                          projectcss.all,
                          sty.primitiveLabel2
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gmoSo
                          )}
                        >
                          {"Password *"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"input3"}
                        data-plasmic-override={overrides.input3}
                        className={classNames(projectcss.all, sty.input3)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__p118J
                          )}
                        >
                          {"************"}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"forgotPassword"}
                    data-plasmic-override={overrides.forgotPassword}
                    className={classNames(projectcss.all, sty.forgotPassword)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___7Jmdv
                      )}
                      component={Link}
                      href={`/forgot-password`}
                      platform={"nextjs"}
                    >
                      {"Forgot password?"}
                    </PlasmicLink__>
                  </div>
                </div>
                <div
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames(projectcss.all, sty.button)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1Vxz
                    )}
                  >
                    {"Login"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"secondaryAction"}
                  data-plasmic-override={overrides.secondaryAction}
                  className={classNames(projectcss.all, sty.secondaryAction)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7N7Tk
                    )}
                  >
                    {"New User? "}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___9Vlpa
                    )}
                    component={Link}
                    href={`/signup`}
                    platform={"nextjs"}
                  >
                    {"Signup"}
                  </PlasmicLink__>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "logIn",
    "container",
    "image",
    "content",
    "title",
    "form",
    "input",
    "container2",
    "primitiveLabel",
    "input2",
    "container3",
    "primitiveLabel2",
    "input3",
    "forgotPassword",
    "button",
    "secondaryAction"
  ],
  logIn: [
    "logIn",
    "container",
    "image",
    "content",
    "title",
    "form",
    "input",
    "container2",
    "primitiveLabel",
    "input2",
    "container3",
    "primitiveLabel2",
    "input3",
    "forgotPassword",
    "button",
    "secondaryAction"
  ],
  container: [
    "container",
    "image",
    "content",
    "title",
    "form",
    "input",
    "container2",
    "primitiveLabel",
    "input2",
    "container3",
    "primitiveLabel2",
    "input3",
    "forgotPassword",
    "button",
    "secondaryAction"
  ],
  image: ["image"],
  content: [
    "content",
    "title",
    "form",
    "input",
    "container2",
    "primitiveLabel",
    "input2",
    "container3",
    "primitiveLabel2",
    "input3",
    "forgotPassword",
    "button",
    "secondaryAction"
  ],
  title: ["title"],
  form: [
    "form",
    "input",
    "container2",
    "primitiveLabel",
    "input2",
    "container3",
    "primitiveLabel2",
    "input3",
    "forgotPassword"
  ],
  input: [
    "input",
    "container2",
    "primitiveLabel",
    "input2",
    "container3",
    "primitiveLabel2",
    "input3"
  ],
  container2: ["container2", "primitiveLabel", "input2"],
  primitiveLabel: ["primitiveLabel"],
  input2: ["input2"],
  container3: ["container3", "primitiveLabel2", "input3"],
  primitiveLabel2: ["primitiveLabel2"],
  input3: ["input3"],
  forgotPassword: ["forgotPassword"],
  button: ["button"],
  secondaryAction: ["secondaryAction"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  logIn: "div";
  container: "div";
  image: "div";
  content: "div";
  title: "div";
  form: "div";
  input: "div";
  container2: "div";
  primitiveLabel: "div";
  input2: "div";
  container3: "div";
  primitiveLabel2: "div";
  input3: "div";
  forgotPassword: "div";
  button: "div";
  secondaryAction: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLogin__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLogin__VariantsArgs;
    args?: PlasmicLogin__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLogin__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLogin__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLogin__ArgProps,
          internalVariantPropNames: PlasmicLogin__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLogin__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLogin";
  } else {
    func.displayName = `PlasmicLogin.${nodeName}`;
  }
  return func;
}

export const PlasmicLogin = Object.assign(
  // Top-level PlasmicLogin renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    logIn: makeNodeComponent("logIn"),
    container: makeNodeComponent("container"),
    image: makeNodeComponent("image"),
    content: makeNodeComponent("content"),
    title: makeNodeComponent("title"),
    form: makeNodeComponent("form"),
    input: makeNodeComponent("input"),
    container2: makeNodeComponent("container2"),
    primitiveLabel: makeNodeComponent("primitiveLabel"),
    input2: makeNodeComponent("input2"),
    container3: makeNodeComponent("container3"),
    primitiveLabel2: makeNodeComponent("primitiveLabel2"),
    input3: makeNodeComponent("input3"),
    forgotPassword: makeNodeComponent("forgotPassword"),
    button: makeNodeComponent("button"),
    secondaryAction: makeNodeComponent("secondaryAction"),

    // Metadata about props expected for PlasmicLogin
    internalVariantProps: PlasmicLogin__VariantProps,
    internalArgProps: PlasmicLogin__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicLogin;
/* prettier-ignore-end */
