/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: onkH1pA6HdPM1JMb3Mte45
// Component: bPH3oQCa_ryB

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: onkH1pA6HdPM1JMb3Mte45/projectcss
import sty from "./PlasmicOurDevelopments.module.css"; // plasmic-import: bPH3oQCa_ryB/css

import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: Dmi5ztWZ87DU/icon
import MdiUserIcon from "./icons/PlasmicIcon__MdiUser"; // plasmic-import: dUaFGneMe7i2/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: EB1OGIZsE2Kn/icon
import Vector1Icon from "./icons/PlasmicIcon__Vector1"; // plasmic-import: f68eVSSD6GHl/icon
import Icon7Icon from "./icons/PlasmicIcon__Icon7"; // plasmic-import: 6qGWRE-38yD0/icon
import Ellipse1Icon from "./icons/PlasmicIcon__Ellipse1"; // plasmic-import: Fknml35cGAKj/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: LDQJEZ4Irw3G/icon
import ArrowIcon from "./icons/PlasmicIcon__Arrow"; // plasmic-import: LrzIpY4AIRk_/icon
import Vector3Icon from "./icons/PlasmicIcon__Vector3"; // plasmic-import: FXwN8v7ffwYj/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: GcRKLpV7Su8j/icon

createPlasmicElementProxy;

export type PlasmicOurDevelopments__VariantMembers = {};
export type PlasmicOurDevelopments__VariantsArgs = {};
type VariantPropType = keyof PlasmicOurDevelopments__VariantsArgs;
export const PlasmicOurDevelopments__VariantProps =
  new Array<VariantPropType>();

export type PlasmicOurDevelopments__ArgsType = {};
type ArgPropType = keyof PlasmicOurDevelopments__ArgsType;
export const PlasmicOurDevelopments__ArgProps = new Array<ArgPropType>();

export type PlasmicOurDevelopments__OverridesType = {
  root?: Flex__<"div">;
  ourDevelopments?: Flex__<"div">;
  headerHeroSection?: Flex__<"div">;
  header?: Flex__<"div">;
  container?: Flex__<"div">;
  logo?: Flex__<"div">;
  logoMark?: Flex__<"div">;
  navigationMenu?: Flex__<"div">;
  link?: Flex__<"div">;
  link2?: Flex__<"div">;
  link3?: Flex__<"div">;
  link4?: Flex__<"div">;
  link5?: Flex__<"div">;
  button?: Flex__<"button">;
  heroSection?: Flex__<"div">;
  container2?: Flex__<"div">;
  experienceTheFutureOfLuxuryLivingAcrossAfri?: Flex__<"div">;
  developments?: Flex__<"div">;
  halfBg?: Flex__<"div">;
  results?: Flex__<"div">;
  title?: Flex__<"div">;
  badge?: Flex__<"div">;
  content?: Flex__<"div">;
  tabs?: Flex__<"div">;
  tab?: Flex__<"div">;
  title2?: Flex__<"div">;
  options?: Flex__<"div">;
  _1?: Flex__<"div">;
  _2?: Flex__<"div">;
  _3?: Flex__<"div">;
  _4?: Flex__<"div">;
  _5?: Flex__<"div">;
  cards?: Flex__<"div">;
  cards2?: Flex__<"div">;
  card?: Flex__<"div">;
  imageWithFallback?: Flex__<"div">;
  description?: Flex__<"div">;
  text?: Flex__<"div">;
  title3?: Flex__<"div">;
  units?: Flex__<"div">;
  _6?: Flex__<"div">;
  _7?: Flex__<"div">;
  button2?: Flex__<"div">;
  card2?: Flex__<"div">;
  imageWithFallback2?: Flex__<"div">;
  description2?: Flex__<"div">;
  text2?: Flex__<"div">;
  title4?: Flex__<"div">;
  units2?: Flex__<"div">;
  _8?: Flex__<"div">;
  _9?: Flex__<"div">;
  button3?: Flex__<"div">;
  viewMore?: Flex__<"div">;
  pagination?: Flex__<"div">;
  number?: Flex__<"div">;
  _10?: Flex__<"div">;
  _11?: Flex__<"div">;
  _12?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  footer?: Flex__<"div">;
  container3?: Flex__<"div">;
  left?: Flex__<"div">;
  logo2?: Flex__<"div">;
  logo3?: Flex__<"div">;
  logoMark2?: Flex__<"div">;
  texts?: Flex__<"div">;
  paragraph?: Flex__<"div">;
  paragraph2?: Flex__<"div">;
  right?: Flex__<"div">;
  container4?: Flex__<"div">;
  header2?: Flex__<"div">;
  list?: Flex__<"div">;
  listItem?: Flex__<"div">;
  link6?: Flex__<"div">;
  listItem2?: Flex__<"div">;
  link7?: Flex__<"div">;
  listItem3?: Flex__<"div">;
  link8?: Flex__<"div">;
  listItem4?: Flex__<"div">;
  link9?: Flex__<"div">;
  container5?: Flex__<"div">;
  header3?: Flex__<"div">;
  list2?: Flex__<"div">;
  listItem5?: Flex__<"div">;
  listItem6?: Flex__<"div">;
  container6?: Flex__<"div">;
  link10?: Flex__<"div">;
  link11?: Flex__<"div">;
  link12?: Flex__<"div">;
  container7?: Flex__<"div">;
  container8?: Flex__<"div">;
  paragraph3?: Flex__<"div">;
  _2025HouseNo5ByAfriNestAllRightsReserve?: Flex__<"div">;
  container9?: Flex__<"div">;
  text3?: Flex__<"div">;
  link13?: Flex__<"div">;
  link14?: Flex__<"div">;
  link15?: Flex__<"div">;
  aiChatbot?: Flex__<"div">;
  up?: Flex__<"div">;
  title5?: Flex__<"div">;
  textarea?: Flex__<"div">;
  down?: Flex__<"div">;
  quickPrompts?: Flex__<"div">;
  _13?: Flex__<"button">;
  _14?: Flex__<"button">;
  icon?: Flex__<"div">;
};

export interface DefaultOurDevelopmentsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicOurDevelopments__RenderFunc(props: {
  variants: PlasmicOurDevelopments__VariantsArgs;
  args: PlasmicOurDevelopments__ArgsType;
  overrides: PlasmicOurDevelopments__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"ourDevelopments"}
            data-plasmic-override={overrides.ourDevelopments}
            className={classNames(projectcss.all, sty.ourDevelopments)}
          >
            <div
              data-plasmic-name={"headerHeroSection"}
              data-plasmic-override={overrides.headerHeroSection}
              className={classNames(projectcss.all, sty.headerHeroSection)}
            >
              <div
                data-plasmic-name={"header"}
                data-plasmic-override={overrides.header}
                className={classNames(projectcss.all, sty.header)}
              >
                <div
                  data-plasmic-name={"container"}
                  data-plasmic-override={overrides.container}
                  className={classNames(projectcss.all, sty.container)}
                >
                  <div
                    data-plasmic-name={"logo"}
                    data-plasmic-override={overrides.logo}
                    className={classNames(projectcss.all, sty.logo)}
                  >
                    <div
                      data-plasmic-name={"logoMark"}
                      data-plasmic-override={overrides.logoMark}
                      className={classNames(projectcss.all, sty.logoMark)}
                    >
                      <VectorIcon
                        className={classNames(projectcss.all, sty.svg___85BhB)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mVdqI
                        )}
                      >
                        {"5"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___50Jl3
                      )}
                    >
                      {"HOUSE NO. 5"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"navigationMenu"}
                    data-plasmic-override={overrides.navigationMenu}
                    className={classNames(projectcss.all, sty.navigationMenu)}
                  >
                    <div
                      data-plasmic-name={"link"}
                      data-plasmic-override={overrides.link}
                      className={classNames(projectcss.all, sty.link)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__rcN4E
                        )}
                        component={Link}
                        href={`/`}
                        platform={"nextjs"}
                      >
                        {"Home"}
                      </PlasmicLink__>
                    </div>
                    <div
                      data-plasmic-name={"link2"}
                      data-plasmic-override={overrides.link2}
                      className={classNames(projectcss.all, sty.link2)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___5MLql
                        )}
                        component={Link}
                        href={`/our-developments`}
                        platform={"nextjs"}
                      >
                        {"Our Developments"}
                      </PlasmicLink__>
                    </div>
                    <div
                      data-plasmic-name={"link3"}
                      data-plasmic-override={overrides.link3}
                      className={classNames(projectcss.all, sty.link3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__twda
                        )}
                      >
                        {"About"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"link4"}
                      data-plasmic-override={overrides.link4}
                      className={classNames(projectcss.all, sty.link4)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cynea
                        )}
                      >
                        {"Smart Living"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"link5"}
                      data-plasmic-override={overrides.link5}
                      className={classNames(projectcss.all, sty.link5)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tk58J
                        )}
                      >
                        {"Contact"}
                      </div>
                    </div>
                  </div>
                  <button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      sty.button
                    )}
                    ref={ref => {
                      $refs["button"] = ref;
                    }}
                  >
                    <MdiUserIcon
                      className={classNames(projectcss.all, sty.svg___6QhL0)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rnxZe
                      )}
                    >
                      {"name@example.com"}
                    </div>
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__y2Q0A)}
                      role={"img"}
                    />
                  </button>
                </div>
              </div>
              <div
                data-plasmic-name={"heroSection"}
                data-plasmic-override={overrides.heroSection}
                className={classNames(projectcss.all, sty.heroSection)}
              >
                <div
                  data-plasmic-name={"container2"}
                  data-plasmic-override={overrides.container2}
                  className={classNames(projectcss.all, sty.container2)}
                >
                  <div
                    data-plasmic-name={
                      "experienceTheFutureOfLuxuryLivingAcrossAfri"
                    }
                    data-plasmic-override={
                      overrides.experienceTheFutureOfLuxuryLivingAcrossAfri
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.experienceTheFutureOfLuxuryLivingAcrossAfri
                    )}
                  >
                    {"Neo-Classical Smart Cities Across Africa"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yiM3P
                    )}
                  >
                    {"Elegant. Sustainable. African."}
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"developments"}
              data-plasmic-override={overrides.developments}
              className={classNames(projectcss.all, sty.developments)}
            >
              <div
                data-plasmic-name={"halfBg"}
                data-plasmic-override={overrides.halfBg}
                className={classNames(projectcss.all, sty.halfBg)}
              >
                <div
                  data-plasmic-name={"results"}
                  data-plasmic-override={overrides.results}
                  className={classNames(projectcss.all, sty.results)}
                >
                  <div
                    data-plasmic-name={"title"}
                    data-plasmic-override={overrides.title}
                    className={classNames(projectcss.all, sty.title)}
                  >
                    <div
                      data-plasmic-name={"badge"}
                      data-plasmic-override={overrides.badge}
                      className={classNames(projectcss.all, sty.badge)}
                    >
                      <Vector1Icon
                        className={classNames(projectcss.all, sty.svg__sW7)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___39KFn
                        )}
                      >
                        {"Our Developments"}
                      </div>
                    </div>
                    {false ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__r4Al4
                        )}
                      >
                        {"Nigeria Developments"}
                      </div>
                    ) : null}
                  </div>
                  <div
                    data-plasmic-name={"content"}
                    data-plasmic-override={overrides.content}
                    className={classNames(projectcss.all, sty.content)}
                  >
                    <div
                      data-plasmic-name={"tabs"}
                      data-plasmic-override={overrides.tabs}
                      className={classNames(projectcss.all, sty.tabs)}
                    >
                      <div
                        data-plasmic-name={"tab"}
                        data-plasmic-override={overrides.tab}
                        className={classNames(projectcss.all, sty.tab)}
                      >
                        <div
                          data-plasmic-name={"title2"}
                          data-plasmic-override={overrides.title2}
                          className={classNames(projectcss.all, sty.title2)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__w27HN
                            )}
                          >
                            {"Countries"}
                          </div>
                          <Icon7Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__pk2Ao
                            )}
                            role={"img"}
                          />
                        </div>
                        <div
                          data-plasmic-name={"options"}
                          data-plasmic-override={overrides.options}
                          className={classNames(projectcss.all, sty.options)}
                        >
                          <div
                            data-plasmic-name={"_1"}
                            data-plasmic-override={overrides._1}
                            className={classNames(projectcss.all, sty._1)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___17B0
                              )}
                            >
                              {"Nigeria"}
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"_2"}
                            data-plasmic-override={overrides._2}
                            className={classNames(projectcss.all, sty._2)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__vrT6
                              )}
                            >
                              {"Ghana"}
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"_3"}
                            data-plasmic-override={overrides._3}
                            className={classNames(projectcss.all, sty._3)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___018J3
                              )}
                            >
                              {"Kenya"}
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"_4"}
                            data-plasmic-override={overrides._4}
                            className={classNames(projectcss.all, sty._4)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__yBlfI
                              )}
                            >
                              {"Namibia"}
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"_5"}
                            data-plasmic-override={overrides._5}
                            className={classNames(projectcss.all, sty._5)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__yfTQe
                              )}
                            >
                              {"Angola"}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"cards"}
                      data-plasmic-override={overrides.cards}
                      className={classNames(projectcss.all, sty.cards)}
                    >
                      <div
                        data-plasmic-name={"cards2"}
                        data-plasmic-override={overrides.cards2}
                        className={classNames(projectcss.all, sty.cards2)}
                      >
                        <div
                          data-plasmic-name={"card"}
                          data-plasmic-override={overrides.card}
                          className={classNames(projectcss.all, sty.card)}
                        >
                          <div
                            data-plasmic-name={"imageWithFallback"}
                            data-plasmic-override={overrides.imageWithFallback}
                            className={classNames(
                              projectcss.all,
                              sty.imageWithFallback
                            )}
                          />

                          <div
                            data-plasmic-name={"description"}
                            data-plasmic-override={overrides.description}
                            className={classNames(
                              projectcss.all,
                              sty.description
                            )}
                          >
                            <div
                              data-plasmic-name={"text"}
                              data-plasmic-override={overrides.text}
                              className={classNames(projectcss.all, sty.text)}
                            >
                              <div
                                data-plasmic-name={"title3"}
                                data-plasmic-override={overrides.title3}
                                className={classNames(
                                  projectcss.all,
                                  sty.title3
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__k2Jw6
                                  )}
                                >
                                  {"Jahi Luxury Flat"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"units"}
                                data-plasmic-override={overrides.units}
                                className={classNames(
                                  projectcss.all,
                                  sty.units
                                )}
                              >
                                <div
                                  data-plasmic-name={"_6"}
                                  data-plasmic-override={overrides._6}
                                  className={classNames(projectcss.all, sty._6)}
                                >
                                  <Ellipse1Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__zxyPu
                                    )}
                                    role={"img"}
                                  />

                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__njwM7
                                    )}
                                  >
                                    {"20 Unit Town House"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"_7"}
                                  data-plasmic-override={overrides._7}
                                  className={classNames(projectcss.all, sty._7)}
                                >
                                  <Icon2Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__mDdzt
                                    )}
                                    role={"img"}
                                  />

                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___27U73
                                    )}
                                  >
                                    {"Abuja, Nigeria"}
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"button2"}
                              data-plasmic-override={overrides.button2}
                              className={classNames(
                                projectcss.all,
                                sty.button2
                              )}
                            >
                              <button
                                className={classNames(
                                  projectcss.all,
                                  projectcss.button,
                                  projectcss.__wab_text,
                                  sty.button__r1W1H
                                )}
                              >
                                {"View Details"}
                              </button>
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"card2"}
                          data-plasmic-override={overrides.card2}
                          className={classNames(projectcss.all, sty.card2)}
                        >
                          <div
                            data-plasmic-name={"imageWithFallback2"}
                            data-plasmic-override={overrides.imageWithFallback2}
                            className={classNames(
                              projectcss.all,
                              sty.imageWithFallback2
                            )}
                          />

                          <div
                            data-plasmic-name={"description2"}
                            data-plasmic-override={overrides.description2}
                            className={classNames(
                              projectcss.all,
                              sty.description2
                            )}
                          >
                            <div
                              data-plasmic-name={"text2"}
                              data-plasmic-override={overrides.text2}
                              className={classNames(projectcss.all, sty.text2)}
                            >
                              <div
                                data-plasmic-name={"title4"}
                                data-plasmic-override={overrides.title4}
                                className={classNames(
                                  projectcss.all,
                                  sty.title4
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__qIo85
                                  )}
                                >
                                  {"Jahi Luxury Flat"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"units2"}
                                data-plasmic-override={overrides.units2}
                                className={classNames(
                                  projectcss.all,
                                  sty.units2
                                )}
                              >
                                <div
                                  data-plasmic-name={"_8"}
                                  data-plasmic-override={overrides._8}
                                  className={classNames(projectcss.all, sty._8)}
                                >
                                  <Ellipse1Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__ayslw
                                    )}
                                    role={"img"}
                                  />

                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__f1ARv
                                    )}
                                  >
                                    {"20 Unit Town House"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"_9"}
                                  data-plasmic-override={overrides._9}
                                  className={classNames(projectcss.all, sty._9)}
                                >
                                  <Icon2Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__iyc6H
                                    )}
                                    role={"img"}
                                  />

                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__gIw7W
                                    )}
                                  >
                                    {"Abuja, Nigeria"}
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"button3"}
                              data-plasmic-override={overrides.button3}
                              className={classNames(
                                projectcss.all,
                                sty.button3
                              )}
                            >
                              <button
                                className={classNames(
                                  projectcss.all,
                                  projectcss.button,
                                  projectcss.__wab_text,
                                  sty.button__nAkd1
                                )}
                              >
                                {"View Details"}
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"viewMore"}
                        data-plasmic-override={overrides.viewMore}
                        className={classNames(projectcss.all, sty.viewMore)}
                      >
                        <div
                          data-plasmic-name={"pagination"}
                          data-plasmic-override={overrides.pagination}
                          className={classNames(projectcss.all, sty.pagination)}
                        >
                          <ArrowIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__nocb
                            )}
                            role={"img"}
                          />

                          <div
                            data-plasmic-name={"number"}
                            data-plasmic-override={overrides.number}
                            className={classNames(projectcss.all, sty.number)}
                          >
                            <div
                              data-plasmic-name={"_10"}
                              data-plasmic-override={overrides._10}
                              className={classNames(projectcss.all, sty._10)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__gTeEy
                                )}
                              >
                                {"1"}
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"_11"}
                              data-plasmic-override={overrides._11}
                              className={classNames(projectcss.all, sty._11)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__rDzJo
                                )}
                              >
                                {"2"}
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"_12"}
                              data-plasmic-override={overrides._12}
                              className={classNames(projectcss.all, sty._12)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__xBr
                                )}
                              >
                                {"3"}
                              </div>
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"freeBox"}
                            data-plasmic-override={overrides.freeBox}
                            className={classNames(projectcss.all, sty.freeBox)}
                          >
                            <ArrowIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__zi3I
                              )}
                              role={"img"}
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(projectcss.all, sty.footer)}
            >
              <div
                data-plasmic-name={"container3"}
                data-plasmic-override={overrides.container3}
                className={classNames(projectcss.all, sty.container3)}
              >
                <div
                  data-plasmic-name={"left"}
                  data-plasmic-override={overrides.left}
                  className={classNames(projectcss.all, sty.left)}
                >
                  <div
                    data-plasmic-name={"logo2"}
                    data-plasmic-override={overrides.logo2}
                    className={classNames(projectcss.all, sty.logo2)}
                  >
                    <div
                      data-plasmic-name={"logo3"}
                      data-plasmic-override={overrides.logo3}
                      className={classNames(projectcss.all, sty.logo3)}
                    >
                      <div
                        data-plasmic-name={"logoMark2"}
                        data-plasmic-override={overrides.logoMark2}
                        className={classNames(projectcss.all, sty.logoMark2)}
                      >
                        <Vector3Icon
                          className={classNames(projectcss.all, sty.svg___7U6S)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xdAYp
                          )}
                        >
                          {"5"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3ByUl
                        )}
                      >
                        {"HOUSE NO. 5"}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"texts"}
                    data-plasmic-override={overrides.texts}
                    className={classNames(projectcss.all, sty.texts)}
                  >
                    <div
                      data-plasmic-name={"paragraph"}
                      data-plasmic-override={overrides.paragraph}
                      className={classNames(projectcss.all, sty.paragraph)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zVu2
                        )}
                      >
                        {"Elegant. Sustainable. African."}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"paragraph2"}
                      data-plasmic-override={overrides.paragraph2}
                      className={classNames(projectcss.all, sty.paragraph2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mrN
                        )}
                      >
                        {"Premium smart city developments across Africa."}
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"right"}
                  data-plasmic-override={overrides.right}
                  className={classNames(projectcss.all, sty.right)}
                >
                  <div
                    data-plasmic-name={"container4"}
                    data-plasmic-override={overrides.container4}
                    className={classNames(projectcss.all, sty.container4)}
                  >
                    <div
                      data-plasmic-name={"header2"}
                      data-plasmic-override={overrides.header2}
                      className={classNames(projectcss.all, sty.header2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qiCry
                        )}
                      >
                        {"Quick Links"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"list"}
                      data-plasmic-override={overrides.list}
                      className={classNames(projectcss.all, sty.list)}
                    >
                      <div
                        data-plasmic-name={"listItem"}
                        data-plasmic-override={overrides.listItem}
                        className={classNames(projectcss.all, sty.listItem)}
                      >
                        <div
                          data-plasmic-name={"link6"}
                          data-plasmic-override={overrides.link6}
                          className={classNames(projectcss.all, sty.link6)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___8TlWu
                            )}
                          >
                            {"Browse Estates"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"listItem2"}
                        data-plasmic-override={overrides.listItem2}
                        className={classNames(projectcss.all, sty.listItem2)}
                      >
                        <div
                          data-plasmic-name={"link7"}
                          data-plasmic-override={overrides.link7}
                          className={classNames(projectcss.all, sty.link7)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___3RXu9
                            )}
                          >
                            {"About Us"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"listItem3"}
                        data-plasmic-override={overrides.listItem3}
                        className={classNames(projectcss.all, sty.listItem3)}
                      >
                        <div
                          data-plasmic-name={"link8"}
                          data-plasmic-override={overrides.link8}
                          className={classNames(projectcss.all, sty.link8)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__cafFx
                            )}
                          >
                            {"Smart Living"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"listItem4"}
                        data-plasmic-override={overrides.listItem4}
                        className={classNames(projectcss.all, sty.listItem4)}
                      >
                        <div
                          data-plasmic-name={"link9"}
                          data-plasmic-override={overrides.link9}
                          className={classNames(projectcss.all, sty.link9)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__sfEnN
                            )}
                          >
                            {"Contact"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"container5"}
                    data-plasmic-override={overrides.container5}
                    className={classNames(projectcss.all, sty.container5)}
                  >
                    <div
                      data-plasmic-name={"header3"}
                      data-plasmic-override={overrides.header3}
                      className={classNames(projectcss.all, sty.header3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tpOeH
                        )}
                      >
                        {"Connect"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"list2"}
                      data-plasmic-override={overrides.list2}
                      className={classNames(projectcss.all, sty.list2)}
                    >
                      <div
                        data-plasmic-name={"listItem5"}
                        data-plasmic-override={overrides.listItem5}
                        className={classNames(projectcss.all, sty.listItem5)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dqzs5
                          )}
                        >
                          {"info@houseno5.com"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"listItem6"}
                        data-plasmic-override={overrides.listItem6}
                        className={classNames(projectcss.all, sty.listItem6)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9Drh1
                          )}
                        >
                          {"+1 (555) 123-4567"}
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"container6"}
                      data-plasmic-override={overrides.container6}
                      className={classNames(projectcss.all, sty.container6)}
                    >
                      <div
                        data-plasmic-name={"link10"}
                        data-plasmic-override={overrides.link10}
                        className={classNames(projectcss.all, sty.link10)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___4Nzhi
                          )}
                        >
                          {"LinkedIn"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"link11"}
                        data-plasmic-override={overrides.link11}
                        className={classNames(projectcss.all, sty.link11)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fDe7M
                          )}
                        >
                          {"Instagram"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"link12"}
                        data-plasmic-override={overrides.link12}
                        className={classNames(projectcss.all, sty.link12)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vXw7
                          )}
                        >
                          {"Twitter"}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"container7"}
                data-plasmic-override={overrides.container7}
                className={classNames(projectcss.all, sty.container7)}
              >
                <div
                  data-plasmic-name={"container8"}
                  data-plasmic-override={overrides.container8}
                  className={classNames(projectcss.all, sty.container8)}
                >
                  <div
                    data-plasmic-name={"paragraph3"}
                    data-plasmic-override={overrides.paragraph3}
                    className={classNames(projectcss.all, sty.paragraph3)}
                  >
                    <div
                      data-plasmic-name={
                        "_2025HouseNo5ByAfriNestAllRightsReserve"
                      }
                      data-plasmic-override={
                        overrides._2025HouseNo5ByAfriNestAllRightsReserve
                      }
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty._2025HouseNo5ByAfriNestAllRightsReserve
                      )}
                    >
                      {
                        "\u00a9 2025 House No. 5 by AfriNest. All rights reserved."
                      }
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"container9"}
                    data-plasmic-override={overrides.container9}
                    className={classNames(projectcss.all, sty.container9)}
                  >
                    <div
                      data-plasmic-name={"text3"}
                      data-plasmic-override={overrides.text3}
                      className={classNames(projectcss.all, sty.text3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bQgD
                        )}
                      >
                        {"Sister Brands:"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"link13"}
                      data-plasmic-override={overrides.link13}
                      className={classNames(projectcss.all, sty.link13)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__isHqA
                        )}
                      >
                        {"AfriNest"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"link14"}
                      data-plasmic-override={overrides.link14}
                      className={classNames(projectcss.all, sty.link14)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___8B1Uy
                        )}
                      >
                        {"Urban Edge"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"link15"}
                      data-plasmic-override={overrides.link15}
                      className={classNames(projectcss.all, sty.link15)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mhn4Y
                        )}
                      >
                        {"Green Haven"}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"aiChatbot"}
              data-plasmic-override={overrides.aiChatbot}
              className={classNames(projectcss.all, sty.aiChatbot)}
            >
              <div
                data-plasmic-name={"up"}
                data-plasmic-override={overrides.up}
                className={classNames(projectcss.all, sty.up)}
              >
                <div
                  data-plasmic-name={"title5"}
                  data-plasmic-override={overrides.title5}
                  className={classNames(projectcss.all, sty.title5)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ctjNb
                    )}
                  >
                    {"Ask Esi about Jahi"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"textarea"}
                  data-plasmic-override={overrides.textarea}
                  className={classNames(projectcss.all, sty.textarea)}
                >
                  <textarea
                    className={classNames(
                      projectcss.all,
                      projectcss.textarea,
                      projectcss.__wab_text,
                      sty.textarea__n3GbP
                    )}
                    placeholder={"Write your prompt"}
                  >
                    {"Write your prompt|"}
                  </textarea>
                </div>
              </div>
              <div
                data-plasmic-name={"down"}
                data-plasmic-override={overrides.down}
                className={classNames(projectcss.all, sty.down)}
              >
                <div
                  data-plasmic-name={"quickPrompts"}
                  data-plasmic-override={overrides.quickPrompts}
                  className={classNames(projectcss.all, sty.quickPrompts)}
                >
                  <button
                    data-plasmic-name={"_13"}
                    data-plasmic-override={overrides._13}
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      sty._13
                    )}
                    ref={ref => {
                      $refs["_13"] = ref;
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hw13
                      )}
                    >
                      {"Show me 2-bed options"}
                    </div>
                  </button>
                  <button
                    data-plasmic-name={"_14"}
                    data-plasmic-override={overrides._14}
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      sty._14
                    )}
                    ref={ref => {
                      $refs["_14"] = ref;
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__h6Dh
                      )}
                    >
                      {"Show me 2-bed options"}
                    </div>
                  </button>
                  <div
                    data-plasmic-name={"icon"}
                    data-plasmic-override={overrides.icon}
                    className={classNames(projectcss.all, sty.icon)}
                  >
                    <Icon8Icon
                      className={classNames(projectcss.all, sty.svg__aAzPy)}
                      role={"img"}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "ourDevelopments",
    "headerHeroSection",
    "header",
    "container",
    "logo",
    "logoMark",
    "navigationMenu",
    "link",
    "link2",
    "link3",
    "link4",
    "link5",
    "button",
    "heroSection",
    "container2",
    "experienceTheFutureOfLuxuryLivingAcrossAfri",
    "developments",
    "halfBg",
    "results",
    "title",
    "badge",
    "content",
    "tabs",
    "tab",
    "title2",
    "options",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "cards",
    "cards2",
    "card",
    "imageWithFallback",
    "description",
    "text",
    "title3",
    "units",
    "_6",
    "_7",
    "button2",
    "card2",
    "imageWithFallback2",
    "description2",
    "text2",
    "title4",
    "units2",
    "_8",
    "_9",
    "button3",
    "viewMore",
    "pagination",
    "number",
    "_10",
    "_11",
    "_12",
    "freeBox",
    "footer",
    "container3",
    "left",
    "logo2",
    "logo3",
    "logoMark2",
    "texts",
    "paragraph",
    "paragraph2",
    "right",
    "container4",
    "header2",
    "list",
    "listItem",
    "link6",
    "listItem2",
    "link7",
    "listItem3",
    "link8",
    "listItem4",
    "link9",
    "container5",
    "header3",
    "list2",
    "listItem5",
    "listItem6",
    "container6",
    "link10",
    "link11",
    "link12",
    "container7",
    "container8",
    "paragraph3",
    "_2025HouseNo5ByAfriNestAllRightsReserve",
    "container9",
    "text3",
    "link13",
    "link14",
    "link15",
    "aiChatbot",
    "up",
    "title5",
    "textarea",
    "down",
    "quickPrompts",
    "_13",
    "_14",
    "icon"
  ],
  ourDevelopments: [
    "ourDevelopments",
    "headerHeroSection",
    "header",
    "container",
    "logo",
    "logoMark",
    "navigationMenu",
    "link",
    "link2",
    "link3",
    "link4",
    "link5",
    "button",
    "heroSection",
    "container2",
    "experienceTheFutureOfLuxuryLivingAcrossAfri",
    "developments",
    "halfBg",
    "results",
    "title",
    "badge",
    "content",
    "tabs",
    "tab",
    "title2",
    "options",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "cards",
    "cards2",
    "card",
    "imageWithFallback",
    "description",
    "text",
    "title3",
    "units",
    "_6",
    "_7",
    "button2",
    "card2",
    "imageWithFallback2",
    "description2",
    "text2",
    "title4",
    "units2",
    "_8",
    "_9",
    "button3",
    "viewMore",
    "pagination",
    "number",
    "_10",
    "_11",
    "_12",
    "freeBox",
    "footer",
    "container3",
    "left",
    "logo2",
    "logo3",
    "logoMark2",
    "texts",
    "paragraph",
    "paragraph2",
    "right",
    "container4",
    "header2",
    "list",
    "listItem",
    "link6",
    "listItem2",
    "link7",
    "listItem3",
    "link8",
    "listItem4",
    "link9",
    "container5",
    "header3",
    "list2",
    "listItem5",
    "listItem6",
    "container6",
    "link10",
    "link11",
    "link12",
    "container7",
    "container8",
    "paragraph3",
    "_2025HouseNo5ByAfriNestAllRightsReserve",
    "container9",
    "text3",
    "link13",
    "link14",
    "link15",
    "aiChatbot",
    "up",
    "title5",
    "textarea",
    "down",
    "quickPrompts",
    "_13",
    "_14",
    "icon"
  ],
  headerHeroSection: [
    "headerHeroSection",
    "header",
    "container",
    "logo",
    "logoMark",
    "navigationMenu",
    "link",
    "link2",
    "link3",
    "link4",
    "link5",
    "button",
    "heroSection",
    "container2",
    "experienceTheFutureOfLuxuryLivingAcrossAfri"
  ],
  header: [
    "header",
    "container",
    "logo",
    "logoMark",
    "navigationMenu",
    "link",
    "link2",
    "link3",
    "link4",
    "link5",
    "button"
  ],
  container: [
    "container",
    "logo",
    "logoMark",
    "navigationMenu",
    "link",
    "link2",
    "link3",
    "link4",
    "link5",
    "button"
  ],
  logo: ["logo", "logoMark"],
  logoMark: ["logoMark"],
  navigationMenu: [
    "navigationMenu",
    "link",
    "link2",
    "link3",
    "link4",
    "link5"
  ],
  link: ["link"],
  link2: ["link2"],
  link3: ["link3"],
  link4: ["link4"],
  link5: ["link5"],
  button: ["button"],
  heroSection: [
    "heroSection",
    "container2",
    "experienceTheFutureOfLuxuryLivingAcrossAfri"
  ],
  container2: ["container2", "experienceTheFutureOfLuxuryLivingAcrossAfri"],
  experienceTheFutureOfLuxuryLivingAcrossAfri: [
    "experienceTheFutureOfLuxuryLivingAcrossAfri"
  ],
  developments: [
    "developments",
    "halfBg",
    "results",
    "title",
    "badge",
    "content",
    "tabs",
    "tab",
    "title2",
    "options",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "cards",
    "cards2",
    "card",
    "imageWithFallback",
    "description",
    "text",
    "title3",
    "units",
    "_6",
    "_7",
    "button2",
    "card2",
    "imageWithFallback2",
    "description2",
    "text2",
    "title4",
    "units2",
    "_8",
    "_9",
    "button3",
    "viewMore",
    "pagination",
    "number",
    "_10",
    "_11",
    "_12",
    "freeBox"
  ],
  halfBg: [
    "halfBg",
    "results",
    "title",
    "badge",
    "content",
    "tabs",
    "tab",
    "title2",
    "options",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "cards",
    "cards2",
    "card",
    "imageWithFallback",
    "description",
    "text",
    "title3",
    "units",
    "_6",
    "_7",
    "button2",
    "card2",
    "imageWithFallback2",
    "description2",
    "text2",
    "title4",
    "units2",
    "_8",
    "_9",
    "button3",
    "viewMore",
    "pagination",
    "number",
    "_10",
    "_11",
    "_12",
    "freeBox"
  ],
  results: [
    "results",
    "title",
    "badge",
    "content",
    "tabs",
    "tab",
    "title2",
    "options",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "cards",
    "cards2",
    "card",
    "imageWithFallback",
    "description",
    "text",
    "title3",
    "units",
    "_6",
    "_7",
    "button2",
    "card2",
    "imageWithFallback2",
    "description2",
    "text2",
    "title4",
    "units2",
    "_8",
    "_9",
    "button3",
    "viewMore",
    "pagination",
    "number",
    "_10",
    "_11",
    "_12",
    "freeBox"
  ],
  title: ["title", "badge"],
  badge: ["badge"],
  content: [
    "content",
    "tabs",
    "tab",
    "title2",
    "options",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "cards",
    "cards2",
    "card",
    "imageWithFallback",
    "description",
    "text",
    "title3",
    "units",
    "_6",
    "_7",
    "button2",
    "card2",
    "imageWithFallback2",
    "description2",
    "text2",
    "title4",
    "units2",
    "_8",
    "_9",
    "button3",
    "viewMore",
    "pagination",
    "number",
    "_10",
    "_11",
    "_12",
    "freeBox"
  ],
  tabs: ["tabs", "tab", "title2", "options", "_1", "_2", "_3", "_4", "_5"],
  tab: ["tab", "title2", "options", "_1", "_2", "_3", "_4", "_5"],
  title2: ["title2"],
  options: ["options", "_1", "_2", "_3", "_4", "_5"],
  _1: ["_1"],
  _2: ["_2"],
  _3: ["_3"],
  _4: ["_4"],
  _5: ["_5"],
  cards: [
    "cards",
    "cards2",
    "card",
    "imageWithFallback",
    "description",
    "text",
    "title3",
    "units",
    "_6",
    "_7",
    "button2",
    "card2",
    "imageWithFallback2",
    "description2",
    "text2",
    "title4",
    "units2",
    "_8",
    "_9",
    "button3",
    "viewMore",
    "pagination",
    "number",
    "_10",
    "_11",
    "_12",
    "freeBox"
  ],
  cards2: [
    "cards2",
    "card",
    "imageWithFallback",
    "description",
    "text",
    "title3",
    "units",
    "_6",
    "_7",
    "button2",
    "card2",
    "imageWithFallback2",
    "description2",
    "text2",
    "title4",
    "units2",
    "_8",
    "_9",
    "button3"
  ],
  card: [
    "card",
    "imageWithFallback",
    "description",
    "text",
    "title3",
    "units",
    "_6",
    "_7",
    "button2"
  ],
  imageWithFallback: ["imageWithFallback"],
  description: [
    "description",
    "text",
    "title3",
    "units",
    "_6",
    "_7",
    "button2"
  ],
  text: ["text", "title3", "units", "_6", "_7"],
  title3: ["title3"],
  units: ["units", "_6", "_7"],
  _6: ["_6"],
  _7: ["_7"],
  button2: ["button2"],
  card2: [
    "card2",
    "imageWithFallback2",
    "description2",
    "text2",
    "title4",
    "units2",
    "_8",
    "_9",
    "button3"
  ],
  imageWithFallback2: ["imageWithFallback2"],
  description2: [
    "description2",
    "text2",
    "title4",
    "units2",
    "_8",
    "_9",
    "button3"
  ],
  text2: ["text2", "title4", "units2", "_8", "_9"],
  title4: ["title4"],
  units2: ["units2", "_8", "_9"],
  _8: ["_8"],
  _9: ["_9"],
  button3: ["button3"],
  viewMore: [
    "viewMore",
    "pagination",
    "number",
    "_10",
    "_11",
    "_12",
    "freeBox"
  ],
  pagination: ["pagination", "number", "_10", "_11", "_12", "freeBox"],
  number: ["number", "_10", "_11", "_12"],
  _10: ["_10"],
  _11: ["_11"],
  _12: ["_12"],
  freeBox: ["freeBox"],
  footer: [
    "footer",
    "container3",
    "left",
    "logo2",
    "logo3",
    "logoMark2",
    "texts",
    "paragraph",
    "paragraph2",
    "right",
    "container4",
    "header2",
    "list",
    "listItem",
    "link6",
    "listItem2",
    "link7",
    "listItem3",
    "link8",
    "listItem4",
    "link9",
    "container5",
    "header3",
    "list2",
    "listItem5",
    "listItem6",
    "container6",
    "link10",
    "link11",
    "link12",
    "container7",
    "container8",
    "paragraph3",
    "_2025HouseNo5ByAfriNestAllRightsReserve",
    "container9",
    "text3",
    "link13",
    "link14",
    "link15"
  ],
  container3: [
    "container3",
    "left",
    "logo2",
    "logo3",
    "logoMark2",
    "texts",
    "paragraph",
    "paragraph2",
    "right",
    "container4",
    "header2",
    "list",
    "listItem",
    "link6",
    "listItem2",
    "link7",
    "listItem3",
    "link8",
    "listItem4",
    "link9",
    "container5",
    "header3",
    "list2",
    "listItem5",
    "listItem6",
    "container6",
    "link10",
    "link11",
    "link12"
  ],
  left: [
    "left",
    "logo2",
    "logo3",
    "logoMark2",
    "texts",
    "paragraph",
    "paragraph2"
  ],
  logo2: ["logo2", "logo3", "logoMark2"],
  logo3: ["logo3", "logoMark2"],
  logoMark2: ["logoMark2"],
  texts: ["texts", "paragraph", "paragraph2"],
  paragraph: ["paragraph"],
  paragraph2: ["paragraph2"],
  right: [
    "right",
    "container4",
    "header2",
    "list",
    "listItem",
    "link6",
    "listItem2",
    "link7",
    "listItem3",
    "link8",
    "listItem4",
    "link9",
    "container5",
    "header3",
    "list2",
    "listItem5",
    "listItem6",
    "container6",
    "link10",
    "link11",
    "link12"
  ],
  container4: [
    "container4",
    "header2",
    "list",
    "listItem",
    "link6",
    "listItem2",
    "link7",
    "listItem3",
    "link8",
    "listItem4",
    "link9"
  ],
  header2: ["header2"],
  list: [
    "list",
    "listItem",
    "link6",
    "listItem2",
    "link7",
    "listItem3",
    "link8",
    "listItem4",
    "link9"
  ],
  listItem: ["listItem", "link6"],
  link6: ["link6"],
  listItem2: ["listItem2", "link7"],
  link7: ["link7"],
  listItem3: ["listItem3", "link8"],
  link8: ["link8"],
  listItem4: ["listItem4", "link9"],
  link9: ["link9"],
  container5: [
    "container5",
    "header3",
    "list2",
    "listItem5",
    "listItem6",
    "container6",
    "link10",
    "link11",
    "link12"
  ],
  header3: ["header3"],
  list2: ["list2", "listItem5", "listItem6"],
  listItem5: ["listItem5"],
  listItem6: ["listItem6"],
  container6: ["container6", "link10", "link11", "link12"],
  link10: ["link10"],
  link11: ["link11"],
  link12: ["link12"],
  container7: [
    "container7",
    "container8",
    "paragraph3",
    "_2025HouseNo5ByAfriNestAllRightsReserve",
    "container9",
    "text3",
    "link13",
    "link14",
    "link15"
  ],
  container8: [
    "container8",
    "paragraph3",
    "_2025HouseNo5ByAfriNestAllRightsReserve",
    "container9",
    "text3",
    "link13",
    "link14",
    "link15"
  ],
  paragraph3: ["paragraph3", "_2025HouseNo5ByAfriNestAllRightsReserve"],
  _2025HouseNo5ByAfriNestAllRightsReserve: [
    "_2025HouseNo5ByAfriNestAllRightsReserve"
  ],
  container9: ["container9", "text3", "link13", "link14", "link15"],
  text3: ["text3"],
  link13: ["link13"],
  link14: ["link14"],
  link15: ["link15"],
  aiChatbot: [
    "aiChatbot",
    "up",
    "title5",
    "textarea",
    "down",
    "quickPrompts",
    "_13",
    "_14",
    "icon"
  ],
  up: ["up", "title5", "textarea"],
  title5: ["title5"],
  textarea: ["textarea"],
  down: ["down", "quickPrompts", "_13", "_14", "icon"],
  quickPrompts: ["quickPrompts", "_13", "_14", "icon"],
  _13: ["_13"],
  _14: ["_14"],
  icon: ["icon"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  ourDevelopments: "div";
  headerHeroSection: "div";
  header: "div";
  container: "div";
  logo: "div";
  logoMark: "div";
  navigationMenu: "div";
  link: "div";
  link2: "div";
  link3: "div";
  link4: "div";
  link5: "div";
  button: "button";
  heroSection: "div";
  container2: "div";
  experienceTheFutureOfLuxuryLivingAcrossAfri: "div";
  developments: "div";
  halfBg: "div";
  results: "div";
  title: "div";
  badge: "div";
  content: "div";
  tabs: "div";
  tab: "div";
  title2: "div";
  options: "div";
  _1: "div";
  _2: "div";
  _3: "div";
  _4: "div";
  _5: "div";
  cards: "div";
  cards2: "div";
  card: "div";
  imageWithFallback: "div";
  description: "div";
  text: "div";
  title3: "div";
  units: "div";
  _6: "div";
  _7: "div";
  button2: "div";
  card2: "div";
  imageWithFallback2: "div";
  description2: "div";
  text2: "div";
  title4: "div";
  units2: "div";
  _8: "div";
  _9: "div";
  button3: "div";
  viewMore: "div";
  pagination: "div";
  number: "div";
  _10: "div";
  _11: "div";
  _12: "div";
  freeBox: "div";
  footer: "div";
  container3: "div";
  left: "div";
  logo2: "div";
  logo3: "div";
  logoMark2: "div";
  texts: "div";
  paragraph: "div";
  paragraph2: "div";
  right: "div";
  container4: "div";
  header2: "div";
  list: "div";
  listItem: "div";
  link6: "div";
  listItem2: "div";
  link7: "div";
  listItem3: "div";
  link8: "div";
  listItem4: "div";
  link9: "div";
  container5: "div";
  header3: "div";
  list2: "div";
  listItem5: "div";
  listItem6: "div";
  container6: "div";
  link10: "div";
  link11: "div";
  link12: "div";
  container7: "div";
  container8: "div";
  paragraph3: "div";
  _2025HouseNo5ByAfriNestAllRightsReserve: "div";
  container9: "div";
  text3: "div";
  link13: "div";
  link14: "div";
  link15: "div";
  aiChatbot: "div";
  up: "div";
  title5: "div";
  textarea: "div";
  down: "div";
  quickPrompts: "div";
  _13: "button";
  _14: "button";
  icon: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicOurDevelopments__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicOurDevelopments__VariantsArgs;
    args?: PlasmicOurDevelopments__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicOurDevelopments__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicOurDevelopments__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicOurDevelopments__ArgProps,
          internalVariantPropNames: PlasmicOurDevelopments__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicOurDevelopments__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOurDevelopments";
  } else {
    func.displayName = `PlasmicOurDevelopments.${nodeName}`;
  }
  return func;
}

export const PlasmicOurDevelopments = Object.assign(
  // Top-level PlasmicOurDevelopments renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    ourDevelopments: makeNodeComponent("ourDevelopments"),
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    header: makeNodeComponent("header"),
    container: makeNodeComponent("container"),
    logo: makeNodeComponent("logo"),
    logoMark: makeNodeComponent("logoMark"),
    navigationMenu: makeNodeComponent("navigationMenu"),
    link: makeNodeComponent("link"),
    link2: makeNodeComponent("link2"),
    link3: makeNodeComponent("link3"),
    link4: makeNodeComponent("link4"),
    link5: makeNodeComponent("link5"),
    button: makeNodeComponent("button"),
    heroSection: makeNodeComponent("heroSection"),
    container2: makeNodeComponent("container2"),
    experienceTheFutureOfLuxuryLivingAcrossAfri: makeNodeComponent(
      "experienceTheFutureOfLuxuryLivingAcrossAfri"
    ),
    developments: makeNodeComponent("developments"),
    halfBg: makeNodeComponent("halfBg"),
    results: makeNodeComponent("results"),
    title: makeNodeComponent("title"),
    badge: makeNodeComponent("badge"),
    content: makeNodeComponent("content"),
    tabs: makeNodeComponent("tabs"),
    tab: makeNodeComponent("tab"),
    title2: makeNodeComponent("title2"),
    options: makeNodeComponent("options"),
    _1: makeNodeComponent("_1"),
    _2: makeNodeComponent("_2"),
    _3: makeNodeComponent("_3"),
    _4: makeNodeComponent("_4"),
    _5: makeNodeComponent("_5"),
    cards: makeNodeComponent("cards"),
    cards2: makeNodeComponent("cards2"),
    card: makeNodeComponent("card"),
    imageWithFallback: makeNodeComponent("imageWithFallback"),
    description: makeNodeComponent("description"),
    text: makeNodeComponent("text"),
    title3: makeNodeComponent("title3"),
    units: makeNodeComponent("units"),
    _6: makeNodeComponent("_6"),
    _7: makeNodeComponent("_7"),
    button2: makeNodeComponent("button2"),
    card2: makeNodeComponent("card2"),
    imageWithFallback2: makeNodeComponent("imageWithFallback2"),
    description2: makeNodeComponent("description2"),
    text2: makeNodeComponent("text2"),
    title4: makeNodeComponent("title4"),
    units2: makeNodeComponent("units2"),
    _8: makeNodeComponent("_8"),
    _9: makeNodeComponent("_9"),
    button3: makeNodeComponent("button3"),
    viewMore: makeNodeComponent("viewMore"),
    pagination: makeNodeComponent("pagination"),
    number: makeNodeComponent("number"),
    _10: makeNodeComponent("_10"),
    _11: makeNodeComponent("_11"),
    _12: makeNodeComponent("_12"),
    freeBox: makeNodeComponent("freeBox"),
    footer: makeNodeComponent("footer"),
    container3: makeNodeComponent("container3"),
    left: makeNodeComponent("left"),
    logo2: makeNodeComponent("logo2"),
    logo3: makeNodeComponent("logo3"),
    logoMark2: makeNodeComponent("logoMark2"),
    texts: makeNodeComponent("texts"),
    paragraph: makeNodeComponent("paragraph"),
    paragraph2: makeNodeComponent("paragraph2"),
    right: makeNodeComponent("right"),
    container4: makeNodeComponent("container4"),
    header2: makeNodeComponent("header2"),
    list: makeNodeComponent("list"),
    listItem: makeNodeComponent("listItem"),
    link6: makeNodeComponent("link6"),
    listItem2: makeNodeComponent("listItem2"),
    link7: makeNodeComponent("link7"),
    listItem3: makeNodeComponent("listItem3"),
    link8: makeNodeComponent("link8"),
    listItem4: makeNodeComponent("listItem4"),
    link9: makeNodeComponent("link9"),
    container5: makeNodeComponent("container5"),
    header3: makeNodeComponent("header3"),
    list2: makeNodeComponent("list2"),
    listItem5: makeNodeComponent("listItem5"),
    listItem6: makeNodeComponent("listItem6"),
    container6: makeNodeComponent("container6"),
    link10: makeNodeComponent("link10"),
    link11: makeNodeComponent("link11"),
    link12: makeNodeComponent("link12"),
    container7: makeNodeComponent("container7"),
    container8: makeNodeComponent("container8"),
    paragraph3: makeNodeComponent("paragraph3"),
    _2025HouseNo5ByAfriNestAllRightsReserve: makeNodeComponent(
      "_2025HouseNo5ByAfriNestAllRightsReserve"
    ),
    container9: makeNodeComponent("container9"),
    text3: makeNodeComponent("text3"),
    link13: makeNodeComponent("link13"),
    link14: makeNodeComponent("link14"),
    link15: makeNodeComponent("link15"),
    aiChatbot: makeNodeComponent("aiChatbot"),
    up: makeNodeComponent("up"),
    title5: makeNodeComponent("title5"),
    textarea: makeNodeComponent("textarea"),
    down: makeNodeComponent("down"),
    quickPrompts: makeNodeComponent("quickPrompts"),
    _13: makeNodeComponent("_13"),
    _14: makeNodeComponent("_14"),
    icon: makeNodeComponent("icon"),

    // Metadata about props expected for PlasmicOurDevelopments
    internalVariantProps: PlasmicOurDevelopments__VariantProps,
    internalArgProps: PlasmicOurDevelopments__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicOurDevelopments;
/* prettier-ignore-end */
